sap account-plugin-facebook 		
sap account-plugin-flickr 			
sap account-plugin-jabber  		
sap account-plugin-salut 			
sap account-plugin-twitter  		
sap account-plugin-windows-live  		
sap account-plugin-yahoo 			
sap aptdaemon                        	
sap aptdaemon-data                   	
sap aisleriot 				
sap cups-pk-helper                   	
sap duplicity  				
sap empathy 				
sap empathy-common  			
sap example-content 			
sap gnome-contacts gnome-mahjongg  	
sap gnome-mines 				
sap gnome-orca 				
sap gnome-screensaver  			
sap gnome-sudoku 				
sap gnome-video-effects 			 
sap gnomine 				
sap landscape-common 			
sap libgstreamer-plugins-good1.0-0   	
sap libmpc3                          	
sap libnfnetlink0                    	
sap libreoffice-avmedia-backend-gstreamer 	
sap libreoffice-base-core 			
sap libreoffice-calc 			
sap libreoffice-common  			
sap libreoffice-core 			
sap libreoffice-draw 			
sap libreoffice-gnome 			
sap libreoffice-gtk 			
sap libreoffice-impress  			
sap libreoffice-math 			
sap libreoffice-ogltrans  			
sap libreoffice-pdfimport 			
sap libreoffice-style-galaxy 		
sap libreoffice-style-human 		
sap libreoffice-writer 			
sap libxcb-image0                    	
sap libxcb-keysyms1                  	
sap libxcb-render-util0              	
sap libxcb-util1                     	
sap mcp-account-manager-uoa  		
sap os-prober                        	
sap python3-aptdaemon                	
sap python3-aptdaemon.gtk3widgets    	
sap python3-defer                    	
sap python3-uno 				
sap rhythmbox 				
sap rhythmbox-plugins 			
sap rhythmbox-plugin-zeitgeist 		
sap session-migration	          	
sap shotwell 				
sap shotwell-common 			
sap telepathy-gabble 			
sap telepathy-haze 			
sap telepathy-idle 			
sap telepathy-indicator  			
sap telepathy-logger 			
sap telepathy-mission-control-5  		
sap telepathy-salut 			
sap totem 					
sap totem-common  				
sap totem-plugins				
