#sap adduser                  	
#sap apt                      	
#sap apt-utils                	
#sap bsdmainutils             	
#sap bzip2                    	
#sap ca-certificates          	
#sap console-setup            	
#sap console-setup-linux      	
#sap cpio                     	
#sap dbus                     	
#sap debconf-i18n             	
#sap distro-info-data         	
#sap dmidecode                	
#sap dmsetup                  	
#sap eject                    	
#sap file                     	
#sap gir1.2-glib-2.0          	
#sap gpgv                     	
#sap groff-base               	
#sap info                     	
#sap init                     	
#sap install-info             	
#sap iproute2                 	
#sap iputils-ping             	
#sap isc-dhcp-client          	
#sap isc-dhcp-common          	
#sap kbd                      	
#sap keyboard-configuration   	
#sap kmod                     	
#sap less                     	
#sap libapparmor1             	
#sap libapt-pkg6.0           	
#sap libargon2-1              	
#sap libatm1                  	
#sap libbsd0                  	
#sap libcap2                  	
#sap libcap2-bin              	
#sap libcryptsetup12          	
#sap libdbus-1-3              	
#sap libdevmapper1.02.1       	
#sap libdns-export1109        	
#sap libelf1                  	
#sap libestr0                 	
#sap libexpat1                	
#sap libfastjson4             	
#sap libffi7                  	
#sap libfribidi0              	
#sap libgirepository-1.0-1    	
#sap libglib2.0-0             	
#sap libglib2.0-data          	
#sap libgmp10                 	
#sap libgnutls30              	
#sap libhogweed5              	
#sap libicu66                 	
#sap libidn2-0                	
#sap libip4tc2                	
#sap libisc-export1105        	
#sap libjson-c4               	
#sap libkmod2                 	
#sap liblocale-gettext-perl   	
#sap libmagic1                	
#sap libmagic-mgc             	
#sap libmnl0                  	
#sap libmpdec2                	
#sap libnetplan0              	
#sap libnettle7               	
#sap libnewt0.52              	
#sap libnss-systemd           	
#sap libp11-kit0              	
#sap libpam-cap              	
#sap libpam-systemd           	
#sap libpopt0                 	
#sap libpython3.8-minimal     	
#sap libpython3.8-stdlib      	
#sap libpython3-stdlib        	
#sap libreadline8             	
#sap libseccomp2              	
#sap libslang2                	
#sap libsodium23              	
#sap libsqlite3-0             	
#sap libssl1.1                	
#sap libstdc++6               	
#sap libtasn1-6               	
#sap libtext-charwidth-perl   	
#sap libtext-iconv-perl       	
#sap libtext-wrapi18n-perl    	
#sap libunistring2            	
#sap libxml2                  	
#sap libxtables12             	
#sap libyaml-0-2              	
#sap locales                  	
#sap logrotate                	
#sap lsb-release              	
#sap man-db                   	
#sap mime-support             	
#sap nano                     	
#sap netbase                  	
#sap netcat-openbsd           	
#sap netplan.io               	
#sap networkd-dispatcher      	
#sap openssl                  	
#sap python3                  	
#sap python3.8                	
#sap python3.8-minimal        	
#sap python3-cffi-backend     	
#sap python3-dbus             	
#sap python3-gi               	
#sap python3-minimal          	
#sap python3-nacl             	
#sap python3-netifaces        	
#sap python3-pkg-resources    	
#sap python3-pymacaroons      	
#sap python3-six              	
#sap python3-yaml             	
#sap readline-common          	
#sap rsyslog                  	
#sap shared-mime-info         	
#sap sudo                     	
#sap systemd                  	
#sap systemd-sysv             	
#sap systemd-timesyncd        	
#sap tzdata                   	
#sap ubuntu-advantage-tools   	
#sap ubuntu-keyring           	
#sap ubuntu-minimal           	
#sap ucf                      	
#sap udev                     	
#sap vim-common               	
#sap vim-tiny                 	
#sap whiptail                 	
#sap xdg-user-dirs            	
#sap xkb-data                 	
#sap xxd                      	
#sap xz-utils			
