sap 	#accountsservice \			#optional
sap 	#acl \ 					#optional
sap 	#acpid \ 				#optional
sap 	#acpi-support \ 			#optional
sap 	adwaita-icon-theme \ 			#optional
sap 	#alsa-base \ 				#optional
sap 	#alsa-topology-conf \ 			#optional
sap 	#alsa-ucm-conf \ 			#optional
sap 	#alsa-utils \ 				#optional
sap 	#anacron \ 				#optional
sap 	#apg \ 					#optional
sap 	#apparmor \ 				#optional
sap 	#app-install-data-partner \ 		#optional
sap 	#apport \ 				#optional
sap 	#apport-gtk \ 				#optional
sap 	#apport-symptoms \ 			#optional
sap 	#appstream \ 				#optional
sap 	#apt-config-icons \ 			#optional
sap 	#apt-config-icons-hidpi \ 		#optional
sap 	#apturl \ 				#optional
sap 	#apturl-common \ 			#optional
sap 	#aspell \ 				#optional
sap 	#aspell-en \ 				#optional
sap 	#at-spi2-core \ 		     	#optional
sap 	#avahi-autoipd \ 			#optional
sap 	#avahi-daemon \ 			#optional
sap 	#avahi-utils \ 				#optional
sap 	#bluez \ 				#optional
sap 	#bluez-cups \ 				#optional
sap 	#bluez-obexd \ 				#optional
sap 	#bolt \ 				#optional
sap 	brltty \ 				#optional
sap 	#bubblewrap \ 				#optional
sap 	#busybox-initramfs \ 			#optional
sap 	#busybox-static \ 			#optional
sap 	#cheese-common \ 			#optional
sap 	#colord \ 				#optional
sap 	#colord-data \ 				#optional
sap 	#command-not-found \ 			#optional
sap 	#cpp \ 					#optional
sap 	#cpp-9 \ 				#optional
sap 	#cracklib-runtime \ 			#optional
sap 	#crda \ 				#optional
sap 	#cups \ 				#optional
sap 	#cups-browsed \ 			#optional
sap 	#cups-bsd \ 				#optional
sap 	#cups-client \ 				#optional
sap 	#cups-common \ 				#optional
sap 	#cups-core-drivers \ 			#optional
sap 	#cups-daemon \ 				#optional
sap 	#cups-filters \ 			#optional
sap 	#cups-filters-core-drivers \ 		#optional
sap 	#cups-ipp-utils \ 			#optional
sap 	#cups-ppdc \ 				#optional
sap 	#cups-server-common \ 			#optional
sap 	#dbus-user-session \ 			#optional
sap 	#dbus-x11 \ 				#optional
sap 	#dconf-cli \ 				#optional
sap 	#dconf-gsettings-backend \ 		#optional
sap 	#dconf-service \ 			#optional
sap 	#desktop-file-utils \ 			#optional
sap 	#dictionaries-common \ 			#optional
sap 	#dirmngr \ 				#optional
sap 	#dmz-cursor-theme \ 			#optional
sap 	#dnsmasq-base \ 			#optional
sap 	#dns-root-data \ 			#optional
sap 	#docbook-xml \ 				#optional
sap 	#dosfstools \ 				#optional
sap 	#ed \ 					#optional
sap 	#efibootmgr \ 				#optional
sap 	#emacsen-common \ 			#optional
sap 	#enchant-2 \ 				#optional
sap 	#eog \ 					#optional
sap 	#espeak-ng-data \ 			#optional
sap 	#evince \ 				#optional
sap 	#evince-common \ 			#optional
sap 	#evolution-data-server \ 		#optional
sap 	#evolution-data-server-common \ 	#optional
sap 	#file-roller \ 				#optional
sap 	firefox \ 				#optional
sap 	firefox-locale-en \ 			#optional
sap 	#fontconfig \ 				#optional
sap 	#fontconfig-config \ 			#optional
sap 	fonts-beng \ 				#optional
sap 	fonts-beng-extra \ 			#optional
sap 	#fonts-dejavu-core \ 			#optional
sap 	fonts-deva \ 				#optional
sap 	fonts-deva-extra \ 			#optional
sap 	#fonts-droid-fallback \ 		#optional
sap 	fonts-freefont-ttf \ 			#optional
sap 	fonts-gargi \ 				#optional
sap 	fonts-gubbi \ 				#optional
sap 	fonts-gujr \ 				#optional
sap 	fonts-gujr-extra \ 			#optional
sap 	fonts-guru \ 				#optional
sap 	fonts-guru-extra \ 			#optional
sap 	fonts-indic \ 				#optional
sap 	fonts-kacst \ 				#optional
sap 	fonts-kacst-one \ 			#optional
sap 	fonts-kalapi \ 				#optional
sap 	fonts-khmeros-core \ 			#optional
sap 	fonts-knda \ 				#optional
sap 	fonts-lao \ 				#optional
sap 	fonts-liberation \ 			#optional
sap 	fonts-liberation2 \ 			#optional
sap 	fonts-lklug-sinhala \ 			#optional
sap 	fonts-lohit-beng-assamese \ 		#optional
sap 	fonts-lohit-beng-bengali \ 		#optional
sap 	fonts-lohit-deva \ 			#optional
sap 	fonts-lohit-gujr \ 			#optional
sap 	fonts-lohit-guru \ 			#optional
sap 	fonts-lohit-knda \ 			#optional
sap 	fonts-lohit-mlym \ 			#optional
sap 	fonts-lohit-orya \ 			#optional
sap 	fonts-lohit-taml \ 			#optional
sap 	fonts-lohit-taml-classical \ 		#optional
sap 	fonts-lohit-telu \ 			#optional
sap 	fonts-mlym \ 				#optional
sap 	fonts-nakula \				#optional
sap 	fonts-navilu \ 				#optional
sap 	fonts-noto-cjk \ 			#optional
sap 	fonts-noto-color-emoji \ 		#optional
sap 	#fonts-noto-mono \ 			#optional
sap 	fonts-opensymbol \ 			#optional
sap 	fonts-orya \ 				#optional
sap 	fonts-orya-extra \ 			#optional
sap 	fonts-pagul \ 				#optional
sap 	fonts-sahadeva \ 			#optional
sap 	fonts-samyak-deva \ 			#optional
sap 	fonts-samyak-gujr \ 			#optional
sap 	fonts-samyak-mlym \ 			#optional
sap 	fonts-samyak-taml \ 			#optional
sap 	fonts-sarai \ 				#optional
sap 	fonts-sil-abyssinica \ 			#optional
sap 	fonts-sil-padauk \ 			#optional
sap 	fonts-smc \ 				#optional
sap 	fonts-smc-anjalioldlipi \ 		#optional
sap 	fonts-smc-chilanka \ 			#optional
sap 	fonts-smc-dyuthi \ 			#optional
sap 	fonts-smc-gayathri \ 			#optional
sap 	fonts-smc-karumbi \ 			#optional
sap 	fonts-smc-keraleeyam \ 			#optional
sap 	fonts-smc-manjari \ 			#optional
sap 	fonts-smc-meera \ 			#optional
sap 	fonts-smc-rachana \ 			#optional
sap 	fonts-smc-raghumalayalamsans \ 		#optional
sap 	fonts-smc-suruma \ 			#optional
sap 	fonts-smc-uroob \ 			#optional
sap 	fonts-taml \ 				#optional
sap 	fonts-telu \ 				#optional
sap 	fonts-telu-extra \ 			#optional
sap 	fonts-thai-tlwg \ 			#optional
sap 	fonts-tibetan-machine \ 		#optional
sap 	fonts-tlwg-garuda \ 			#optional
sap 	fonts-tlwg-garuda-ttf \ 		#optional
sap 	fonts-tlwg-kinnari \ 			#optional
sap 	fonts-tlwg-kinnari-ttf \ 		#optional
sap 	fonts-tlwg-laksaman \ 			#optional
sap 	fonts-tlwg-laksaman-ttf \ 		#optional
sap 	fonts-tlwg-loma \ 			#optional
sap 	fonts-tlwg-loma-ttf \ 			#optional
sap 	fonts-tlwg-mono \ 			#optional
sap 	fonts-tlwg-mono-ttf \ 			#optional
sap 	fonts-tlwg-norasi \ 			#optional
sap 	fonts-tlwg-norasi-ttf \ 		#optional
sap 	fonts-tlwg-purisa \ 			#optional
sap 	fonts-tlwg-purisa-ttf \ 		#optional
sap 	fonts-tlwg-sawasdee \ 			#optional
sap 	fonts-tlwg-sawasdee-ttf \ 		#optional
sap 	fonts-tlwg-typewriter \ 		#optional
sap 	fonts-tlwg-typewriter-ttf \ 		#optional
sap 	fonts-tlwg-typist \ 			#optional
sap 	fonts-tlwg-typist-ttf \ 		#optional
sap 	fonts-tlwg-typo \ 			#optional
sap 	fonts-tlwg-typo-ttf \ 			#optional
sap 	fonts-tlwg-umpush \ 			#optional
sap 	fonts-tlwg-umpush-ttf \ 		#optional
sap 	fonts-tlwg-waree \ 			#optional
sap 	fonts-tlwg-waree-ttf \ 			#optional
sap 	fonts-ubuntu \ 				#optional
sap 	fonts-urw-base35 \ 			#optional
sap 	fonts-yrsa-rasa \ 			#optional
sap 	#foomatic-db-compressed-ppds \ 		#optional
sap 	#fprintd \ 				#optional
sap 	#friendly-recovery \ 			#optional
sap 	#fuse \ 				#optional
sap 	#fwupd \ 				#optional
sap 	#fwupd-signed \ 			#optional
sap 	gamemode \ 				#optional
sap 	#gcr \ 					#optional
sap 	#gdb \ 					#optional
sap 	#gdbserver \ 				#optional
sap 	#gdisk \ 				#optional
sap 	#gdm3 \ 				#optional
sap 	gedit \ 				#optional
sap 	gedit-common \ 				#optional
sap 	#genisoimage \ 				#optional
sap 	#geoclue-2.0 \ 				#optional
sap 	#ghostscript \ 				#optional
sap 	#ghostscript-x \ 			#optional
sap 	#gir1.2-accountsservice-1.0 \ 		#optional
sap 	#gir1.2-atk-1.0 \ 			#optional
sap 	#gir1.2-atspi-2.0 \ 			#optional
sap 	#gir1.2-dbusmenu-glib-0.4 \ 		#optional
sap 	#gir1.2-dee-1.0 \ 			#optional
sap 	#gir1.2-freedesktop \ 			#optional
sap 	#gir1.2-gck-1 \ 			#optional
sap 	#gir1.2-gcr-3 \ 			#optional
sap 	#gir1.2-gdesktopenums-3.0 \ 		#optional
sap 	#gir1.2-gdkpixbuf-2.0 \ 		#optional
sap 	#gir1.2-gdm-1.0 \ 			#optional
sap 	#gir1.2-geoclue-2.0 \ 			#optional
sap 	#gir1.2-gmenu-3.0 \ 			#optional
sap 	#gir1.2-gnomebluetooth-1.0 \ 		#optional
sap 	#gir1.2-gnomedesktop-3.0 \ 		#optional
sap 	#gir1.2-goa-1.0 \ 			#optional
sap 	#gir1.2-graphene-1.0 \ 			#optional
sap 	#gir1.2-gstreamer-1.0 \ 		#optional
sap 	#gir1.2-gtk-3.0 \ 			#optional
sap 	#gir1.2-gtksource-4 \ 			#optional
sap 	#gir1.2-gweather-3.0 \ 			#optional
sap 	#gir1.2-ibus-1.0 \ 			#optional
sap 	#gir1.2-javascriptcoregtk-4.0 \ 	#optional
sap 	#gir1.2-json-1.0 \ 			#optional
sap 	#gir1.2-mutter-6 \ 			#optional
sap 	#gir1.2-nm-1.0 \ 			#optional
sap 	#gir1.2-nma-1.0 \ 			#optional
sap 	#gir1.2-notify-0.7 \ 			#optional
sap 	#gir1.2-packagekitglib-1.0 \ 		#optional
sap 	#gir1.2-pango-1.0 \			#optional
sap 	#gir1.2-peas-1.0 \ 			#optional
sap 	#gir1.2-polkit-1.0 \ 			#optional
sap 	#gir1.2-rsvg-2.0 \ 			#optional
sap 	#gir1.2-secret-1 \ 			#optional
sap 	#gir1.2-snapd-1 \ 			#optional
sap 	#gir1.2-soup-2.4 \ 			#optional
sap 	#gir1.2-unity-5.0 \ 			#optional
sap 	#gir1.2-upowerglib-1.0 \ 		#optional
sap 	#gir1.2-vte-2.91 \ 			#optional
sap 	#gir1.2-webkit2-4.0 \ 			#optional
sap 	#gir1.2-wnck-3.0 \ 			#optional
sap 	git \ 					#optional
sap 	git-man \ 				#optional
sap 	#gjs \ 					#optional
sap 	#gkbd-capplet \ 			#optional
sap 	#glib-networking \ 			#optional
sap 	#glib-networking-common \ 		#optional
sap 	#glib-networking-services \ 		#optional
sap 	gnome-accessibility-themes \ 		#optional
sap 	gnome-bluetooth \ 			#optional
sap 	gnome-calculator \ 			#optional
sap 	gnome-characters \ 			#optional
sap 	gnome-control-center \ 			#optional
sap 	gnome-control-center-data \ 		#optional
sap 	gnome-control-center-faces \ 		#optional
sap 	gnome-desktop3-data \ 			#optional
sap 	gnome-disk-utility \ 			#optional
sap 	gnome-font-viewer \ 			#optional
sap 	gnome-getting-started-docs \ 		#optional
sap 	gnome-initial-setup \ 			#optional
sap 	gnome-keyring \ 			#optional
sap 	gnome-keyring-pkcs11 \ 			#optional
sap 	gnome-logs \ 				#optional
sap 	gnome-menus \ 				#optional
sap 	gnome-online-accounts \ 		#optional
sap 	gnome-power-manager \ 			#optional
sap 	gnome-screenshot \ 			#optional
sap 	gnome-session-bin \ 			#optional
sap 	gnome-session-canberra \ 		#optional
sap 	gnome-session-common \ 			#optional
sap 	gnome-settings-daemon \ 		#optional
sap 	gnome-settings-daemon-common \ 		#optional
sap 	gnome-shell \ 				#optional
sap 	gnome-shell-common \ 			#optional
sap 	gnome-shell-extension-appindicator \ 	#optional
sap 	gnome-shell-extension-desktop-icons \	#optional
sap 	gnome-shell-extension-ubuntu-dock \ 	#optional
sap 	gnome-startup-applications \ 		#optional
sap 	gnome-system-monitor \ 			#optional
sap 	gnome-terminal \ 			#optional
sap 	gnome-terminal-data \ 			#optional
sap 	gnome-themes-extra \ 			#optional
sap 	gnome-themes-extra-data \ 		#optional
sap 	gnome-user-docs \ 			#optional
sap 	#gnupg \ 				#optional
sap 	#gnupg-l10n \ 				#optional
sap 	#gnupg-utils \ 				#optional
sap 	#gpg \ 					#optional
sap 	#gpg-agent \ 				#optional
sap 	#gpgconf \ 				#optional
sap 	#gpgsm \ 				#optional
sap 	#gpg-wks-client \ 			#optional
sap 	#gpg-wks-server \ 			#optional
sap 	#grub2-common \ 			#optional
sap 	#grub-common \ 				#optional
sap 	#grub-efi-amd64-bin \ 			#optional
sap 	#grub-efi-amd64-signed \ 		#optional
sap 	#grub-gfxpayload-lists \ 		#optional
sap 	#grub-pc \ 				#optional
sap 	#grub-pc-bin \ 				#optional
sap 	#gsettings-desktop-schemas \ 		#optional
sap 	#gsettings-ubuntu-schemas \ 		#optional
sap 	#gstreamer1.0-alsa \ 			#optional
sap 	#gstreamer1.0-clutter-3.0 \ 		#optional
sap 	#gstreamer1.0-gl \ 			#optional
sap 	#gstreamer1.0-packagekit \ 		#optional
sap 	#gstreamer1.0-plugins-base \ 		#optional
sap 	#gstreamer1.0-plugins-base-apps \ 	#optional
sap 	#gstreamer1.0-plugins-good \ 		#optional
sap 	#gstreamer1.0-pulseaudio \ 		#optional
sap 	#gstreamer1.0-tools \ 			#optional
sap 	#gstreamer1.0-x \ 			#optional
sap 	#gtk2-engines-murrine \ 		#optional
sap 	#gtk2-engines-pixbuf \ 			#optional
sap 	#gtk-update-icon-cache \ 		#optional
sap 	#gvfs \ 				#optional
sap 	#gvfs-backends \ 			#optional
sap 	#gvfs-bin \ 				#optional
sap 	#gvfs-common \ 				#optional
sap 	#gvfs-daemons \ 			#optional
sap 	#gvfs-fuse \ 				#optional
sap 	#gvfs-libs \ 				#optional
sap 	#hdparm \ 				#optional
sap 	#hicolor-icon-theme \ 			#optional
sap 	#humanity-icon-theme \ 			#optional
sap 	#ibus \ 				#optional
sap 	#ibus-data \ 				#optional
sap 	#ibus-gtk \ 				#optional
sap 	#ibus-gtk3 \ 				#optional
sap 	#ibus-table \ 				#optional
sap 	#iio-sensor-proxy \ 			#optional
sap 	#im-config \ 				#optional
sap 	#initramfs-tools \ 			#optional
sap 	#initramfs-tools-bin \ 			#optional
sap 	#initramfs-tools-core \ 		#optional
sap 	#inputattach \ 				#optional
sap 	#ippusbxd \ 				#optional
sap 	#iptables \ 				#optional
sap 	#iputils-tracepath \ 			#optional
sap 	#irqbalance \ 				#optional
sap 	#iso-codes \ 				#optional
sap 	#iucode-tool \ 				#optional
sap 	#iw \ 					#optional
sap 	#kerneloops \ 				#optional
sap 	#klibc-utils \ 				#optional
sap 	#krb5-locales \ 			#optional
sap 	#language-pack-en \ 			#optional
sap 	#language-pack-en-base \ 		#optional
sap 	#language-pack-gnome-en \ 		#optional
sap 	#language-pack-gnome-en-base \ 		#optional
sap 	#language-selector-common \ 		#optional
sap 	#language-selector-gnome \ 		#optional
sap 	#laptop-detect \ 			#optional
sap 	#libaa1 \ 				#optional
sap 	#libaccountsservice0 \ 			#optional
sap 	#libamtk-5-0 \ 				#optional
sap 	#libamtk-5-common \ 			#optional
sap 	#libao4 \ 				#optional
sap 	#libao-common \ 			#optional
sap 	#libappindicator3-1 \ 			#optional
sap 	#libappstream4 \ 			#optional
sap 	#libarchive13 \ 			#optional
sap 	#libasn1-8-heimdal \ 			#optional
sap 	#libasound2 \ 				#optional
sap 	#libasound2-data \ 			#optional
sap 	#libasound2-plugins \ 			#optional
sap 	#libaspell15 \ 				#optional
sap 	#libassuan0 \ 				#optional
sap 	#libasyncns0 \ 				#optional
sap 	#libatasmart4 \ 			#optional
sap 	#libatk1.0-0 \ 				#optional
sap 	#libatk1.0-data \ 			#optional
sap 	#libatk-adaptor \ 			#optional
sap 	#libatk-bridge2.0-0 \ 			#optional
sap 	#libatkmm-1.6-1v5 \ 			#optional
sap 	#libatopology2 \ 			#optional
sap 	#libatspi2.0-0 \ 			#optional
sap 	#libauthen-sasl-perl \ 			#optional
sap 	#libavahi-client3 \ 			#optional
sap 	#libavahi-common3 \ 			#optional
sap 	#libavahi-common-data \ 		#optional
sap 	#libavahi-core7 \ 			#optional
sap 	#libavahi-glib1 \ 			#optional
sap 	#libavc1394-0 \ 			#optional
sap 	#libbabeltrace1 \ 			#optional
sap 	#libblockdev2 \ 			#optional
sap 	#libblockdev-crypto2 \ 			#optional
sap 	#libblockdev-fs2 \ 			#optional
sap 	#libblockdev-loop2 \ 			#optional
sap 	#libblockdev-part2 \ 			#optional
sap 	#libblockdev-part-err2 \ 		#optional
sap 	#libblockdev-swap2 \ 			#optional
sap 	#libblockdev-utils2 \ 			#optional
sap 	#libbluetooth3 \ 			#optional
sap 	#libboost-thread1.71.0 \ 		#optional
sap 	#libbrlapi0.7 \ 			#optional
sap 	#libbrotli1 \ 				#optional
sap 	#libc6-dbg \ 				#optional
sap 	#libcaca0 \ 				#optional
sap 	#libcairo2 \ 				#optional
sap 	#libcairo-gobject2 \ 			#optional
sap 	#libcairo-gobject-perl \ 		#optional
sap 	#libcairomm-1.0-1v5 \ 			#optional
sap 	#libcairo-perl \ 			#optional
sap 	#libcamel-1.2-62 \ 			#optional
sap 	#libcanberra0 \ 			#optional
sap 	#libcanberra-gtk3-0 \             	#optional
sap 	#libcanberra-gtk3-module \ 		#optional
sap 	#libcanberra-pulse \ 			#optional
sap 	#libcbor0.6 \ 				#optional
sap 	#libcc1-0 \ 				#optional
sap 	#libcdio18 \ 				#optional
sap 	#libcdio-cdda2 \ 			#optional
sap 	#libcdio-paranoia2 \ 			#optional
sap 	#libcdparanoia0 \ 			#optional
sap 	#libcheese8 \ 				#optional
sap 	#libcheese-gtk25 \ 			#optional
sap 	#libclutter-1.0-0 \ 			#optional
sap 	#libclutter-1.0-common \ 		#optional
sap 	#libclutter-gst-3.0-0 \ 		#optional
sap 	#libclutter-gtk-1.0-0 \ 		#optional
sap 	#libcogl20 \ 				#optional
sap 	#libcogl-common \ 			#optional
sap 	#libcogl-pango20 \ 			#optional
sap 	#libcogl-path20 \ 			#optional
sap 	#libcolord2 \ 				#optional
sap 	#libcolord-gtk1 \ 			#optional
sap 	#libcolorhug2 \ 			#optional
sap 	#libcrack2 \ 				#optional
sap 	#libcue2 \ 				#optional
sap 	#libcups2 \ 				#optional
sap 	#libcupsfilters1 \ 			#optional
sap 	#libcupsimage2 \ 			#optional
sap 	#libcurl3-gnutls \ 			#optional
sap 	#libdaemon0 \ 				#optional
sap 	#libdata-dump-perl \ 			#optional
sap 	#libdatrie1 \ 				#optional
sap 	#libdbus-glib-1-2 \ 			#optional
sap 	#libdbusmenu-glib4 \ 			#optional
sap 	#libdbusmenu-gtk3-4 \ 			#optional
sap 	#libdconf1 \ 				#optional
sap 	#libdee-1.0-4 \ 			#optional
sap 	#libdjvulibre21 \ 			#optional
sap 	#libdjvulibre-text \ 			#optional
sap 	#libdotconf0 \ 				#optional
sap 	#libdpkg-perl \ 			#optional
sap 	#libdrm2 \ 				#optional
sap 	#libdrm-amdgpu1 \ 			#optional
sap 	#libdrm-common \ 			#optional
sap 	#libdrm-intel1 \ 			#optional
sap 	#libdrm-nouveau2 \ 			#optional
sap 	#libdrm-radeon1 \ 			#optional
sap 	#libdv4 \ 				#optional
sap 	#libdw1 \ 				#optional
sap 	#libebackend-1.2-10 \ 			#optional
sap 	#libebook-1.2-20 \ 			#optional
sap 	#libebook-contacts-1.2-3 \ 		#optional
sap 	#libecal-2.0-1 \ 			#optional
sap 	#libedata-book-1.2-26 \ 		#optional
sap 	#libedata-cal-2.0-1 \ 			#optional
sap 	#libedataserver-1.2-24 \ 		#optional
sap 	#libedataserverui-1.2-2 \ 		#optional
sap 	#libedit2 \ 				#optional
sap 	#libefiboot1 \ 				#optional
sap 	#libefivar1 \ 				#optional
sap 	#libegl1 \ 				#optional
sap 	#libegl-mesa0 \ 			#optional
sap 	#libenchant-2-2 \ 			#optional
sap 	#libencode-locale-perl \ 		#optional
sap 	#libepoxy0 \ 				#optional
sap 	#liberror-perl \ 			#optional
sap 	#libespeak-ng1 \ 			#optional
sap 	#libevdev2 \ 				#optional
sap 	#libevdocument3-4 \ 			#optional
sap 	#libevview3-3 \ 			#optional
sap 	#libexempi8 \ 				#optional
sap 	#libexif12 \ 				#optional
sap 	#libexiv2-27 \ 				#optional
sap 	#libextutils-depends-perl \ 		#optional
sap 	#libextutils-pkgconfig-perl \ 		#optional
sap 	#libfftw3-single3 \ 			#optional
sap 	#libfido2-1 \ 				#optional
sap 	#libfile-basedir-perl \ 		#optional
sap 	#libfile-desktopentry-perl \ 		#optional
sap 	#libfile-fcntllock-perl \ 		#optional
sap 	#libfile-listing-perl \ 		#optional
sap 	#libfile-mimeinfo-perl \ 		#optional
sap 	#libflac8 \ 				#optional
sap 	#libfont-afm-perl \ 			#optional
sap 	#libfontconfig1 \ 			#optional
sap 	#libfontembed1 \ 			#optional
sap 	#libfontenc1 \ 				#optional
sap 	#libfprint-2-2 \ 			#optional
sap 	#libfreetype6 \ 			#optional
sap 	#libfuse2 \ 				#optional
sap 	#libfwupd2 \ 				#optional
sap 	#libfwupdplugin1 \ 			#optional
sap 	#libgail18 \ 				#optional
sap 	#libgail-common \ 			#optional
sap 	#libgamemode0 \ 			#optional
sap 	#libgamemodeauto0 \ 			#optional
sap 	#libgbm1 \ 				#optional
sap 	#libgcab-1.0-0 \ 			#optional
sap 	#libgck-1-0 \ 				#optional
sap 	#libgcr-base-3-1 \			#optional
sap 	#libgcr-ui-3-1 \ 			#optional
sap 	#libgd3 \ 				#optional
sap 	#libgdata22 \ 				#optional
sap 	#libgdata-common \ 			#optional
sap 	#libgdbm6 \ 				#optional
sap 	#libgdbm-compat4 \ 			#optional
sap 	#libgdk-pixbuf2.0-0 \ 			#optional
sap 	#libgdk-pixbuf2.0-bin \ 		#optional
sap 	#libgdk-pixbuf2.0-common \ 		#optional
sap 	#libgdm1 \ 				#optional
sap 	#libgee-0.8-2 \ 			#optional
sap 	#libgeoclue-2-0 \ 			#optional
sap 	#libgeocode-glib0 \ 			#optional
sap 	#libgexiv2-2 \ 				#optional
sap 	#libgif7 \ 				#optional
sap 	#libgjs0g \ 				#optional
sap 	#libgl1 \ 				#optional
sap 	#libgl1-mesa-dri \ 			#optional
sap 	#libglapi-mesa \ 			#optional
sap 	#libgles2 \ 				#optional
sap 	#libglib2.0-bin \ 			#optional
sap 	#libglibmm-2.4-1v5 \ 			#optional
sap 	#libglib-object-introspection-perl \ 	#optional
sap 	#libglib-perl \ 			#optional
sap 	#libglu1-mesa \ 			#optional
sap 	#libglvnd0 \ 				#optional
sap 	#libglx0 \ 				#optional
sap 	#libglx-mesa0 \ 			#optional
sap 	#libgnome-autoar-0-0 \ 			#optional
sap 	#libgnome-bluetooth13 \ 		#optional
sap 	#libgnome-desktop-3-19 \ 		#optional
sap 	#libgnomekbd8 \ 			#optional
sap 	#libgnomekbd-common \ 			#optional
sap 	#libgnome-menu-3-0 \ 			#optional
sap 	#libgoa-1.0-0b \ 			#optional
sap 	#libgoa-1.0-common \ 			#optional
sap 	#libgoa-backend-1.0-1 \ 		#optional
sap 	#libgomp1 \ 				#optional
sap 	#libgpgme11 \ 				#optional
sap 	#libgphoto2-6 \ 			#optional
sap 	#libgphoto2-l10n \ 			#optional
sap 	#libgphoto2-port12 \ 			#optional
sap 	#libgpm2 \ 				#optional
sap 	#libgraphene-1.0-0 \ 			#optional
sap 	#libgraphite2-3 \ 			#optional
sap 	#libgs9 \ 				#optional
sap 	#libgs9-common \ 			#optional
sap 	#libgsf-1-114 \ 			#optional
sap 	#libgsf-1-common \ 			#optional
sap 	#libgsound0 \ 				#optional
sap 	#libgspell-1-2 \ 			#optional
sap 	#libgspell-1-common \ 			#optional
sap 	#libgssapi3-heimdal \ 			#optional
sap 	#libgssapi-krb5-2 \ 			#optional
sap 	#libgssdp-1.2-0 \ 			#optional
sap 	#libgstreamer1.0-0 \ 			#optional
sap 	#libgstreamer-gl1.0-0 \ 		#optional
sap 	#libgstreamer-plugins-base1.0-0 \ 	#optional
sap 	#libgtk2.0-0 \ 				#optional
sap 	#libgtk2.0-bin \ 			#optional
sap 	#libgtk2.0-common \ 			#optional
sap 	#libgtk-3-0 \ 				#optional
sap 	#libgtk-3-bin \ 			#optional
sap 	#libgtk-3-common \ 			#optional
sap 	#libgtk3-perl \ 			#optional
sap 	#libgtkmm-3.0-1v5 \ 			#optional
sap 	#libgtksourceview-4-0 \ 		#optional
sap 	#libgtksourceview-4-common \ 		#optional
sap 	#libgtop-2.0-11 \ 			#optional
sap 	#libgtop2-common \ 			#optional
sap 	#libgudev-1.0-0 \ 			#optional
sap 	#libgupnp-1.2-0 \ 			#optional
sap 	#libgupnp-av-1.0-2 \ 			#optional
sap 	#libgupnp-dlna-2.0-3 \ 			#optional
sap 	#libgusb2 \ 				#optional
sap 	#libgweather-3-16 \ 			#optional
sap 	#libgweather-common \ 			#optional
sap 	#libgxps2 \ 				#optional
sap 	#libhandy-0.0-0 \ 			#optional
sap 	#libharfbuzz0b \ 			#optional
sap 	#libharfbuzz-icu0 \ 			#optional
sap 	#libhcrypto4-heimdal \ 			#optional
sap 	#libheimbase1-heimdal \ 		#optional
sap 	#libheimntlm0-heimdal \ 		#optional
sap 	#libhtml-format-perl \ 			#optional
sap 	#libhtml-form-perl \ 			#optional
sap 	#libhtml-parser-perl \ 			#optional
sap 	#libhtml-tagset-perl \ 			#optional
sap 	#libhtml-tree-perl \ 			#optional
sap 	#libhttp-cookies-perl \ 		#optional
sap 	#libhttp-daemon-perl \ 			#optional
sap 	#libhttp-date-perl \ 			#optional
sap 	#libhttp-message-perl \ 		#optional
sap 	#libhttp-negotiate-perl \ 		#optional
sap 	#libhunspell-1.7-0 \ 			#optional
sap 	#libhx509-5-heimdal \ 			#optional
sap 	#libhyphen0 \ 				#optional
sap 	#libibus-1.0-5 \ 			#optional
sap 	#libical3 \ 				#optional
sap 	#libice6 \ 				#optional
sap 	#libidn11 \ 				#optional
sap 	#libiec61883-0 \ 			#optional
sap 	#libieee1284-3 \ 			#optional
sap 	#libijs-0.35 \ 				#optional
sap 	#libimobiledevice6 \ 			#optional
sap 	#libinput10 \ 				#optional
sap 	#libinput-bin \ 			#optional
sap 	#libio-html-perl \ 			#optional
sap 	#libio-socket-ssl-perl \ 		#optional
sap 	#libio-stringy-perl \ 			#optional
sap 	#libip6tc2 \ 				#optional
sap 	#libipc-system-simple-perl \ 		#optional
sap 	#libisl22 \ 				#optional
sap 	#libiw30 \ 				#optional
sap 	#libjack-jackd2-0 \ 			#optional
sap 	#libjansson4 \ 				#optional	
sap 	#libjavascriptcoregtk-4.0-18 \ 		#optional
sap 	#libjbig0 \ 				#optional
sap 	#libjbig2dec0 \ 			#optional
sap 	#libjpeg8 \ 				#optional
sap 	#libjpeg-turbo8 \ 			#optional
sap 	#libjson-glib-1.0-0 \ 			#optional
sap 	#libjson-glib-1.0-common \ 		#optional
sap 	#libk5crypto3 \ 			#optional
sap 	#libkeyutils1 \ 			#optional
sap 	#libklibc \ 				#optional
sap 	#libkpathsea6 \ 			#optional
sap 	#libkrb5-26-heimdal \ 			#optional
sap 	#libkrb5-3 \ 				#optional
sap 	#libkrb5support0 \ 			#optional
sap 	#libksba8 \ 				#optional
sap 	#liblcms2-2 \ 				#optional
sap 	#liblcms2-utils \ 			#optional
sap 	#libldap-2.4-2 \ 			#optional
sap 	#libldap-common \ 			#optional
sap 	#libldb2 \ 				#optional
sap 	#libllvm10 \ 				#optional
sap 	#libllvm9 \ 				#optional
sap 	#liblmdb0 \ 				#optional
sap 	#liblouis20 \ 				#optional
sap 	#liblouis-data \ 			#optional
sap 	#liblouisutdml9 \ 			#optional
sap 	#liblouisutdml-bin \ 			#optional
sap 	#liblouisutdml-data \ 			#optional
sap 	#libltdl7 \ 				#optional
sap 	#liblwp-mediatypes-perl \ 		#optional
sap 	#liblwp-protocol-https-perl \ 		#optional
sap 	#liblzo2-2 \ 				#optional
sap 	#libmailtools-perl \ 			#optional
sap 	#libmaxminddb0 \ 			#optional
sap 	#libmbim-glib4 \ 			#optional
sap 	#libmbim-proxy \ 			#optional
sap 	#libmediaart-2.0-0 \ 			#optional
sap 	#libmm-glib0 \ 				#optional
sap 	#libmozjs-68-0 \ 			#optional
sap 	#libmp3lame0 \ 				#optional
sap 	#libmpfr6 \ 				#optional
sap 	#libmpg123-0 \ 				#optional
sap 	#libmtdev1 \ 				#optional
sap 	#libmtp9 \ 				#optional
sap 	#libmtp-common \ 			#optional
sap 	#libmtp-runtime \ 			#optional
sap 	#libmutter-6-0 \ 			#optional
sap 	#libmysqlclient21 \ 			#optional
sap 	#libnautilus-extension1a \ 		#optional
sap 	#libndp0 \ 				#optional
sap 	#libnet-dbus-perl \ 			#optional
sap 	#libnetfilter-conntrack3 \ 		#optional
sap 	#libnet-http-perl \ 			#optional
sap 	#libnet-smtp-ssl-perl \ 		#optional
sap 	#libnet-ssleay-perl \ 			#optional
sap 	#libnfs13 \ 				#optional
sap 	#libnftnl11 \ 				#optional
sap 	#libnghttp2-14 \ 			#optional
sap 	#libnl-3-200 \ 				#optional
sap 	#libnl-genl-3-200 \ 			#optional
sap 	#libnl-route-3-200 \ 			#optional
sap 	#libnm0 \ 				#optional
sap 	#libnma0 \ 				#optional
sap 	#libnotify4 \ 				#optional
sap 	#libnotify-bin \ 			#optional
sap 	#libnpth0 \ 				#optional
sap 	#libnspr4 \ 				#optional
sap 	#libnss3 \ 				#optional
sap 	#libnss-mdns \ 				#optional
sap 	#libntfs-3g883 \ 			#optional
sap 	#libnuma1 \ 				#optional
sap 	#libnvpair1linux \ 			#optional
sap 	#libogg0 \ 				#optional
sap 	#libopenjp2-7 \ 			#optional
sap 	#libopus0 \ 				#optional
sap 	#liborc-0.4-0 \ 			#optional
sap 	#libpackagekit-glib2-18 \ 		#optional
sap 	#libpam-fprintd \ 			#optional
sap 	#libpam-gnome-keyring \ 		#optional
sap 	#libpango-1.0-0 \ 			#optional
sap 	#libpangocairo-1.0-0 \ 			#optional
sap 	#libpangoft2-1.0-0 \ 			#optional
sap 	#libpangomm-1.4-1v5 \ 			#optional
sap 	#libpangoxft-1.0-0 \ 			#optional
sap 	#libpaper1 \ 				#optional
sap 	#libpaper-utils \ 			#optional
sap 	#libparted2 \ 				#optional
sap 	#libparted-fs-resize0 \ 		#optional
sap 	#libpcap0.8 \ 				#optional
sap 	#libpcaudio0 \ 				#optional
sap 	#libpci3 \ 				#optional
sap 	#libpciaccess0 \ 			#optional
sap 	#libpcre2-32-0 \ 			#optional
sap 	#libpcsclite1 \ 			#optional
sap 	#libpeas-1.0-0 \ 			#optional
sap 	#libpeas-common \ 			#optional
sap 	#libperl5.30 \ 				#optional
sap 	#libphonenumber7 \ 			#optional
sap 	#libpipeline1 \ 			#optional
sap 	#libpixman-1-0 \ 			#optional
sap 	#libpkcs11-helper1 \ 			#optional
sap 	#libplist3 \ 				#optional
sap 	#libplymouth5 \ 			#optional
sap 	#libpng16-16 \ 				#optional
sap 	#libpolkit-agent-1-0 \ 			#optional
sap 	#libpolkit-gobject-1-0 \ 		#optional
sap 	#libpoppler97 \ 			#optional
sap 	#libpoppler-cpp0v5 \ 			#optional
sap 	#libpoppler-glib8 \ 			#optional
sap 	#libprotobuf17 \ 			#optional
sap 	#libproxy1-plugin-gsettings \ 		#optional
sap 	#libproxy1-plugin-networkmanager \ 	#optional
sap 	#libproxy1v5 \ 				#optional
sap 	#libpsl5 \ 				#optional
sap 	#libpulse0 \ 				#optional
sap 	#libpulsedsp \ 				#optional
sap 	#libpulse-mainloop-glib0 \ 		#optional
sap 	#libpwquality1 \ 			#optional
sap 	#libpwquality-common \ 			#optional
sap 	#libpython3.8 \ 			#optional
sap 	#libqmi-glib5 \ 			#optional
sap 	#libqmi-proxy \ 			#optional
sap 	#libqpdf26 \ 				#optional	
sap 	#libraw1394-11 \ 			#optional
sap 	#librest-0.7-0 \ 			#optional
sap 	#libroken18-heimdal \ 			#optional
sap 	#librsvg2-2 \ 				#optional
sap 	#librsvg2-common \ 			#optional
sap 	#librtmp1 \ 				#optional
sap 	#librygel-core-2.6-2 \ 			#optional
sap 	#librygel-db-2.6-2 \ 			#optional
sap 	#librygel-renderer-2.6-2 \ 		#optional
sap 	#librygel-server-2.6-2 \ 		#optional
sap 	#libsamplerate0 \ 			#optional
sap 	libsane \ 				#optional
sap 	libsane-common \ 			#optional
sap 	#libsane-hpaio \ 			#optional
sap 	#libsasl2-modules \ 			#optional
sap 	#libsbc1 \ 				#optional
sap 	#libsecret-1-0 \ 			#optional
sap 	#libsecret-common \ 			#optional
sap 	#libsensors5 \ 				#optional
sap 	#libsensors-config \ 			#optional
sap 	#libshout3 \ 				#optional
sap 	#libsigc++-2.0-0v5 \ 			#optional
sap 	#libsm6 \ 				#optional
sap 	#libsmbclient \ 			#optional
sap 	#libsmbios-c2 \ 			#optional
sap 	#libsnapd-glib1 \ 			#optional
sap 	#libsndfile1 \ 				#optional
sap 	#libsnmp35 \ 				#optional
sap 	#libsnmp-base \ 			#optional
sap 	#libsonic0 \ 				#optional
sap 	#libsoup2.4-1 \ 			#optional
sap 	#libsoup-gnome2.4-1 \ 			#optional
sap 	#libsoxr0 \ 				#optional
sap 	#libspectre1 \ 				#optional
sap 	#libspeechd2 \ 				#optional
sap 	#libspeex1 \ 				#optional
sap 	#libspeexdsp1 \ 			#optional
sap 	#libssh-4 \ 				#optional
sap 	#libstartup-notification0 \ 		#optional
sap 	#libstemmer0d \ 			#optional
sap 	#libsynctex2 \ 				#optional
sap 	#libsysmetrics1 \ 			#optional
sap 	#libtag1v5 \ 				#optional
sap 	#libtag1v5-vanilla \ 			#optional
sap 	#libtalloc2 \ 				#optional
sap 	#libtdb1 \ 				#optional
sap 	#libteamdctl0 \ 			#optional
sap 	#libtepl-4-0 \ 				#optional
sap 	#libtevent0 \ 				#optional
sap 	#libthai0 \ 				#optional
sap 	#libthai-data \ 			#optional
sap 	#libtheora0 \ 				#optional
sap 	#libtie-ixhash-perl \ 			#optional
sap 	#libtiff5 \ 				#optional
sap 	#libtimedate-perl \ 			#optional
sap 	#libtotem-plparser18 \ 			#optional
sap 	#libtotem-plparser-common \ 		#optional
sap 	#libtracker-control-2.0-0 \ 		#optional
sap 	#libtracker-miner-2.0-0 \ 		#optional
sap 	#libtracker-sparql-2.0-0 \ 		#optional
sap 	#libtry-tiny-perl \ 			#optional
sap 	#libtss2-esys0 \ 			#optional
sap 	#libtwolame0 \ 				#optional
sap 	#libu2f-udev \ 				#optional
sap 	#libuchardet0 \ 			#optional
sap 	#libudisks2-0 \ 			#optional
sap 	#libunity9 \ 				#optional
sap 	#libunity-protocol-private0 \ 		#optional
sap 	#libunity-scopes-json-def-desktop \ 	#optional
sap 	#libunwind8 \ 				#optional
sap 	#libupower-glib3 \ 			#optional
sap 	#liburi-perl \ 				#optional
sap 	#libusb-1.0-0 \ 			#optional
sap 	#libusbmuxd6 \ 				#optional
sap 	#libuutil1linux \ 			#optional
sap 	#libuv1 \ 				#optional
sap 	#libv4l-0 \ 				#optional
sap 	#libv4lconvert0 \ 			#optional
sap 	#libvisual-0.4-0 \ 			#optional
sap 	#libvolume-key1 \ 			#optional
sap 	#libvorbis0a \ 				#optional
sap 	#libvorbisenc2 \ 			#optional
sap 	#libvorbisfile3 \ 			#optional
sap 	#libvpx6 \ 				#optional
sap 	#libvte-2.91-0 \ 			#optional
sap 	#libvte-2.91-common \ 			#optional
sap 	#libvulkan1 \ 				#optional
sap 	#libwacom2 \ 				#optional
sap 	#libwacom-bin \ 			#optional
sap 	#libwacom-common \ 			#optional
sap 	#libwavpack1 \ 				#optional
sap 	#libwayland-client0 \ 			#optional
sap 	#libwayland-cursor0 \ 			#optional
sap 	#libwayland-egl1 \ 			#optional
sap 	#libwayland-server0 \ 			#optional
sap 	#libwbclient0 \ 			#optional
sap 	#libwebkit2gtk-4.0-37 \ 		#optional
sap 	#libwebp6 \ 				#optional
sap 	#libwebpdemux2 \ 			#optional
sap 	#libwebrtc-audio-processing1 \ 		#optional
sap 	#libwhoopsie0 \ 			#optional
sap 	#libwhoopsie-preferences0 \ 		#optional
sap 	#libwind0-heimdal \ 			#optional
sap 	#libwmf0.2-7 \ 				#optional
sap 	#libwmf0.2-7-gtk \ 			#optional
sap 	#libwnck-3-0 \ 				#optional
sap 	#libwnck-3-common \ 			#optional
sap 	#libwoff1 \ 				#optional
sap 	#libwrap0 \ 				#optional
sap 	#libwww-perl \ 				#optional
sap 	#libwww-robotrules-perl \ 		#optional
sap 	#libx11-6 \ 				#optional
sap 	#libx11-data \ 				#optional
sap 	#libx11-protocol-perl \ 		#optional
sap 	#libx11-xcb1 \ 				#optional
sap 	#libxatracker2 \ 			#optional
sap 	#libxau6 \ 				#optional
sap 	#libxaw7 \ 				#optional
sap 	#libxcb1 \ 				#optional
sap 	#libxcb-dri2-0 \ 			#optional
sap 	#libxcb-dri3-0 \ 			#optional
sap 	#libxcb-glx0 \ 				#optional
sap 	#libxcb-icccm4 \ 			#optional
sap 	#libxcb-present0 \ 			#optional
sap 	#libxcb-randr0 \ 			#optional
sap 	#libxcb-render0 \ 			#optional
sap 	#libxcb-res0 \ 				#optional
sap 	#libxcb-shape0 \ 			#optional
sap 	#libxcb-shm0 \ 				#optional
sap 	#libxcb-sync1 \ 			#optional
sap 	#libxcb-xfixes0 \ 			#optional
sap 	#libxcb-xkb1 \ 				#optional
sap 	#libxcb-xv0 \ 				#optional
sap 	#libxcomposite1 \ 			#optional
sap 	#libxcursor1 \ 				#optional
sap 	#libxdamage1 \ 				#optional
sap 	#libxdmcp6 \ 				#optional
sap 	#libxext6 \ 				#optional
sap 	#libxfixes3 \ 				#optional
sap 	#libxfont2 \ 				#optional
sap 	#libxft2 \ 				#optional
sap 	#libxi6 \ 				#optional
sap 	#libxinerama1 \ 			#optional
sap 	#libxkbcommon0 \ 			#optional
sap 	#libxkbcommon-x11-0 \ 			#optional
sap 	#libxkbfile1 \ 				#optional
sap 	#libxklavier16 \ 			#optional
sap 	#libxmlb1 \ 				#optional
sap 	#libxml-parser-perl \ 			#optional
sap 	#libxml-twig-perl \ 			#optional
sap 	#libxml-xpathengine-perl \ 		#optional
sap 	#libxmu6 \ 				#optional
sap 	#libxmuu1 \ 				#optional
sap 	#libxpm4 \ 				#optional
sap 	#libxrandr2 \ 				#optional
sap 	#libxrender1 \ 				#optional
sap 	#libxres1 \ 				#optional
sap 	#libxshmfence1 \ 			#optional
sap 	#libxslt1.1 \ 				#optional
sap 	#libxss1 \ 				#optional
sap 	#libxt6 \ 				#optional
sap 	#libxtst6 \ 				#optional
sap 	#libxv1 \ 				#optional
sap 	#libxvmc1 \ 				#optional
sap 	#libxxf86dga1 \ 			#optional
sap 	#libxxf86vm1 \ 				#optional
sap 	#libyelp0 \ 				#optional
sap 	#libzfs2linux \ 			#optional
sap 	#libzpool2linux \ 			#optional
sap 	#linux-base \ 				#optional
sap 	#linux-firmware \ 			#optional
sap 	#linux-generic-hwe-20.04 \ 		#optional
sap 	#linux-headers-5.4.0-42 \ 		#optional
sap 	#linux-headers-5.4.0-42-generic \ 	#optional
sap 	#linux-headers-5.4.0-48 \ 		#optional
sap 	#linux-headers-5.4.0-48-generic \ 	#optional
sap 	#linux-headers-generic-hwe-20.04 \ 	#optional
sap 	#linux-image-5.4.0-42-generic \ 	#optional
sap 	#linux-image-5.4.0-48-generic \ 	#optional
sap 	#linux-image-generic-hwe-20.04 \ 	#optional
sap 	#linux-modules-5.4.0-42-generic \ 	#optional
sap 	#linux-modules-5.4.0-48-generic \ 	#optional
sap 	#linux-modules-extra-5.4.0-42-generic \ #optional
sap 	#linux-modules-extra-5.4.0-48-generic \ #optional
sap 	#linux-sound-base \ 			#optional
sap 	#lshw \ 				#optional
sap 	#ltrace \ 				#optional
sap 	#lz4 \ 					#optional
sap 	#memtest86+ \ 				#optional
sap 	#mesa-vulkan-drivers \ 			#optional
sap 	#mobile-broadband-provider-info \ 	#optional
sap 	#modemmanager \ 			#optional
sap 	#mokutil \ 				#optional
sap 	#mousetweaks \ 				#optional
sap 	#mscompress \ 				#optional
sap 	#mtools \ 				#optional
sap 	#mtr-tiny \ 				#optional
sap 	#mutter \	 			#optional
sap 	#mutter-common \ 			#optional
sap 	#mysql-common \ 			#optional
sap 	#nautilus \ 				#optional
sap 	#nautilus-data \ 			#optional
sap 	#nautilus-extension-gnome-terminal \ 	#optional
sap 	#nautilus-sendto \ 			#optional
sap 	#nautilus-share \ 			#optional
sap 	#network-manager \ 			#optional
sap 	#network-manager-gnome \ 		#optional
sap 	#network-manager-openvpn \ 		#optional
sap 	#network-manager-openvpn-gnome \ 	#optional
sap 	#network-manager-pptp \ 		#optional
sap 	#network-manager-pptp-gnome \ 		#optional
sap 	#ntfs-3g \ 				#optional
sap 	#openprinting-ppds \			#optional
sap 	#openvpn \ 				#optional
sap 	#orca \ 				#optional
sap 	#p11-kit \ 				#optional
sap 	#p11-kit-modules \ 			#optional
sap 	#packagekit \ 				#optional
sap 	#packagekit-tools \ 			#optional
sap 	#parted \ 				#optional
sap 	#patch \ 				#optional
sap 	#pci.ids \ 				#optional
sap 	#pcmciautils \ 				#optional
sap 	#perl-openssl-defaults \ 		#optional
sap 	#pinentry-curses \ 			#optional
sap 	#pinentry-gnome3 \ 			#optional
sap 	#pkg-config \ 				#optional
sap 	#plymouth \ 				#optional
sap 	#plymouth-label \ 			#optional
sap 	#plymouth-theme-spinner \ 		#optional
sap 	#plymouth-theme-ubuntu-text \ 		#optional
sap 	#policykit-1 \ 				#optional
sap 	#policykit-desktop-privileges \ 	#optional
sap 	#poppler-data \ 			#optional
sap 	#poppler-utils \ 			#optional
sap 	#popularity-contest \ 			#optional
sap 	#powermgmt-base \ 			#optional
sap 	#ppp \ 					#optional
sap 	#pptp-linux \ 				#optional
sap 	printer-driver-brlaser \ 		#optional
sap 	#printer-driver-c2esp \ 		#optional
sap 	printer-driver-foo2zjs \ 		#optional
sap 	printer-driver-foo2zjs-common \ 	#optional
sap 	printer-driver-m2300w \ 		#optional
sap 	#printer-driver-min12xxw \ 		#optional
sap 	#printer-driver-pnm2ppa \ 		#optional
sap 	printer-driver-ptouch \ 		#optional
sap 	#printer-driver-pxljr \ 		#optional
sap 	#printer-driver-sag-gdi \ 		#optional
sap 	printer-driver-splix \ 			#optional
sap 	#psmisc \ 				#optional
sap 	#publicsuffix \ 			#optional
sap 	pulseaudio \ 				#optional
sap 	pulseaudio-module-bluetooth \ 		#optional
sap 	pulseaudio-utils \ 			#optional
sap 	#python3-apport \ 			#optional
sap 	#python3-apt \ 				#optional
sap 	#python3-blinker \ 			#optional
sap 	#python3-brlapi \ 			#optional
sap 	#python3-cairo \ 			#optional
sap 	#python3-certifi \ 			#optional
sap 	#python3-chardet \ 			#optional
sap 	#python3-click \ 			#optional
sap 	#python3-colorama \ 			#optional
sap 	#python3-commandnotfound \ 		#optional
sap 	#python3-cryptography \ 		#optional
sap 	#python3-cups \ 			#optional
sap 	#python3-cupshelpers \ 			#optional
sap 	#python3-dateutil \ 			#optional
sap 	#python3-debconf \ 			#optional
sap 	#python3-debian \ 			#optional
sap 	#python3-distro \ 			#optional
sap 	#python3-distro-info \ 			#optional
sap 	#python3-distupgrade \ 			#optional
sap 	#python3-entrypoints \ 			#optional
sap 	#python3-gdbm \ 			#optional
sap 	#python3-gi-cairo \ 			#optional
sap 	#python3-httplib2 \ 			#optional
sap 	#python3-ibus-1.0 \ 			#optional
sap 	#python3-idna \ 			#optional
sap 	#python3-jwt \ 				#optional
sap 	#python3-keyring \ 			#optional
sap 	#python3-launchpadlib \ 		#optional
sap 	#python3-lazr.restfulclient \ 		#optional
sap 	#python3-lazr.uri \ 			#optional
sap 	#python3-louis \ 			#optional
sap 	#python3-macaroonbakery \ 		#optional
sap 	#python3-oauthlib \ 			#optional
sap 	#python3-problem-report \ 		#optional
sap 	#python3-protobuf \ 			#optional
sap 	#python3-pyatspi \ 			#optional
sap 	#python3-requests \ 			#optional
sap 	#python3-requests-unixsocket \ 		#optional
sap 	#python3-rfc3339 \ 			#optional
sap 	#python3-secretstorage \ 		#optional
sap 	#python3-simplejson \ 			#optional
sap 	#python3-software-properties \ 		#optional
sap 	#python3-speechd \ 			#optional
sap 	#python3-systemd \ 			#optional
sap 	#python3-talloc \ 			#optional
sap 	#python3-tz \ 				#optional
sap 	#python3-update-manager \ 		#optional
sap 	#python3-urllib3 \ 			#optional
sap 	#python3-wadllib \ 			#optional
sap 	#python3-xdg \ 				#optional
sap 	#python3-xkit \ 			#optional
sap 	#python-apt-common \ 			#optional
sap 	#rfkill \ 				#optional
sap 	#rsync \ 				#optional
sap 	#rtkit \ 				#optional
sap 	#rygel \ 				#optional
sap 	#samba-libs \ 				#optional
sap 	sane-utils \ 				#optional
sap 	#sbsigntool \ 				#optional
sap 	#seahorse \ 				#optional
sap 	#secureboot-db \ 			#optional
sap 	#sgml-base \ 				#optional
sap 	#sgml-data \ 				#optional
sap 	#shim \ 				#optional
sap 	#shim-signed \ 				#optional
sap 	#snapd \ 				#optional
sap 	#software-properties-common \ 		#optional
sap 	#software-properties-gtk \ 		#optional
sap 	#sound-icons \ 				#optional
sap 	#sound-theme-freedesktop \ 		#optional
sap 	#speech-dispatcher \ 			#optional
sap 	#speech-dispatcher-audio-plugins \ 	#optional
sap 	#speech-dispatcher-espeak-ng \ 		#optional
sap 	#spice-vdagent \ 			#optional
sap 	#squashfs-tools \ 			#optional
sap 	#ssl-cert \ 				#optional
sap 	#strace \ 				#optional
sap 	#switcheroo-control \ 			#optional
sap 	#system-config-printer \ 		#optional
sap 	#system-config-printer-common \ 	#optional
sap 	#system-config-printer-udev \ 		#optional
sap 	#tcpdump \ 				#optional
sap 	#thermald \ 				#optional
sap 	#tpm-udev \ 				#optional
sap 	#tracker \ 				#optional
sap 	#tracker-extract \ 			#optional
sap 	#tracker-miner-fs \ 			#optional
sap 	#ubuntu-desktop \ 			#optional
sap 	#ubuntu-desktop-minimal \		#optional
sap 	#ubuntu-docs \ 				#optional
sap 	#ubuntu-drivers-common \ 		#optional
sap 	#ubuntu-mono \ 				#optional
sap 	#ubuntu-release-upgrader-core \ 	#optional
sap 	#ubuntu-release-upgrader-gtk \ 		#optional
sap 	#ubuntu-report \ 			#optional
sap 	#ubuntu-session \ 			#optional
sap 	#ubuntu-settings \ 			#optional
sap 	#ubuntu-wallpapers \ 			#optional
sap 	#ubuntu-wallpapers-focal \ 		#optional
sap 	#udisks2 \ 				#optional
sap 	#ufw \ 					#optional
sap 	#unattended-upgrades \ 			#optional
sap 	#unzip \ 				#optional
sap 	#update-inetd \ 			#optional
sap 	#update-manager \ 			#optional
sap 	#update-manager-core \ 			#optional
sap 	#update-notifier \ 			#optional
sap 	#update-notifier-common \ 		#optional
sap 	#upower \ 				#optional
sap 	#usb.ids \ 				#optional
sap 	#usb-modeswitch \ 			#optional
sap 	#usb-modeswitch-data \ 			#optional
sap 	#usbmuxd \ 				#optional
sap 	#usbutils \ 				#optional
sap 	#uuid-runtime \ 			#optional
sap 	#wbritish \ 				#optional
sap 	#whoopsie \ 				#optional
sap 	#whoopsie-preferences \ 		#optional
sap 	#wireless-regdb \ 			#optional
sap 	#wireless-tools \ 			#optional
sap 	#wpasupplicant \ 			#optional
sap 	x11-apps \ 				#optional
sap 	x11-common \ 				#optional
sap 	x11-session-utils \ 			#optional
sap 	x11-utils \ 				#optional
sap 	x11-xkb-utils \ 			#optional
sap 	x11-xserver-utils \ 			#optional
sap 	xauth \ 				#optional
sap 	xbitmaps \ 				#optional
sap 	xbrlapi \ 				#optional
sap 	xcursor-themes \ 			#optional
sap 	#xdg-dbus-proxy \ 			#optional
sap 	#xdg-desktop-portal \ 			#optional
sap 	#xdg-desktop-portal-gtk \ 		#optional
sap 	#xdg-user-dirs-gtk \ 			#optional
sap 	#xdg-utils \ 				#optional
sap 	xfonts-base \ 				#optional
sap 	xfonts-encodings \ 			#optional
sap 	xfonts-scalable \ 			#optional
sap 	xfonts-utils \ 				#optional
sap 	xinit \ 				#optional
sap 	xinput \ 				#optional
sap 	#xml-core \ 				#optional
sap 	xorg \ 					#optional
sap 	xorg-docs-core \ 			#optional
sap 	xserver-common \ 			#optional
sap 	xserver-xephyr \ 			#optional
sap 	xserver-xorg \ 				#optional
sap 	xserver-xorg-core \ 			#optional
sap 	xserver-xorg-input-all \ 		#optional
sap 	xserver-xorg-input-libinput \ 		#optional
sap 	xserver-xorg-input-wacom \ 		#optional
sap 	xserver-xorg-legacy \ 			#optional
sap 	xserver-xorg-video-all \ 		#optional
sap 	xserver-xorg-video-amdgpu \ 		#optional
sap 	xserver-xorg-video-ati \ 		#optional
sap 	xserver-xorg-video-fbdev \ 		#optional
sap 	xserver-xorg-video-intel \ 		#optional
sap 	xserver-xorg-video-nouveau \ 		#optional
sap 	xserver-xorg-video-qxl \ 		#optional
sap 	xserver-xorg-video-radeon \ 		#optional
sap 	xserver-xorg-video-vesa \ 		#optional
sap 	xserver-xorg-video-vmware \ 		#optional
sap 	xul-ext-ubufox \ 			#optional
sap 	#xwayland \ 				#optional
sap 	yaru-theme-gnome-shell \ 		#optional
sap 	yaru-theme-gtk \ 			#optional
sap 	yaru-theme-icon \ 			#optional
sap 	yaru-theme-sound \ 			#optional
sap 	yelp \ 					#optional
sap 	yelp-xsl \ 				#optional
sap 	#zenity \ 				#optional
sap 	#zenity-common \ 			#optional
sap 	#zfs-initramfs \ 			#optional
sap 	#zfsutils-linux \ 			#optional
sap 	#zfs-zed \ 				#optional
sap 	#zip \ 					#optional
sap 	#zsys	 				#optional
