#!

sudo apt purge 
	#accountsservice \			#optional
	#acl \ 					#optional
	#acpid \ 				#optional
	#acpi-support \ 			#optional
	adwaita-icon-theme \ 			#optional
	#alsa-base \ 				#optional
	#alsa-topology-conf \ 			#optional
	#alsa-ucm-conf \ 			#optional
	#alsa-utils \ 				#optional
	#anacron \ 				#optional
	#apg \ 					#optional
	#apparmor \ 				#optional
	#app-install-data-partner \ 		#optional
	#apport \ 				#optional
	#apport-gtk \ 				#optional
	#apport-symptoms \ 			#optional
	#appstream \ 				#optional
	#apt-config-icons \ 			#optional
	#apt-config-icons-hidpi \ 		#optional
	#apturl \ 				#optional
	#apturl-common \ 			#optional
	#aspell \ 				#optional
	#aspell-en \ 				#optional
	#at-spi2-core \ 		     	#optional
	#avahi-autoipd \ 			#optional
	#avahi-daemon \ 			#optional
	#avahi-utils \ 				#optional
	#bluez \ 				#optional
	#bluez-cups \ 				#optional
	#bluez-obexd \ 				#optional
	#bolt \ 				#optional
	brltty \ 				#optional
	#bubblewrap \ 				#optional
	#busybox-initramfs \ 			#optional
	#busybox-static \ 			#optional
	#cheese-common \ 			#optional
	#colord \ 				#optional
	#colord-data \ 				#optional
	#command-not-found \ 			#optional
	#cpp \ 					#optional
	#cpp-9 \ 				#optional
	#cracklib-runtime \ 			#optional
	#crda \ 				#optional
	#cups \ 				#optional
	#cups-browsed \ 			#optional
	#cups-bsd \ 				#optional
	#cups-client \ 				#optional
	#cups-common \ 				#optional
	#cups-core-drivers \ 			#optional
	#cups-daemon \ 				#optional
	#cups-filters \ 			#optional
	#cups-filters-core-drivers \ 		#optional
	#cups-ipp-utils \ 			#optional
	#cups-ppdc \ 				#optional
	#cups-server-common \ 			#optional
	#dbus-user-session \ 			#optional
	#dbus-x11 \ 				#optional
	#dconf-cli \ 				#optional
	#dconf-gsettings-backend \ 		#optional
	#dconf-service \ 			#optional
	#desktop-file-utils \ 			#optional
	#dictionaries-common \ 			#optional
	#dirmngr \ 				#optional
	#dmz-cursor-theme \ 			#optional
	#dnsmasq-base \ 			#optional
	#dns-root-data \ 			#optional
	#docbook-xml \ 				#optional
	#dosfstools \ 				#optional
	#ed \ 					#optional
	#efibootmgr \ 				#optional
	#emacsen-common \ 			#optional
	#enchant-2 \ 				#optional
	#eog \ 					#optional
	#espeak-ng-data \ 			#optional
	#evince \ 				#optional
	#evince-common \ 			#optional
	#evolution-data-server \ 		#optional
	#evolution-data-server-common \ 	#optional
	#file-roller \ 				#optional
	firefox \ 				#optional
	firefox-locale-en \ 			#optional
	#fontconfig \ 				#optional
	#fontconfig-config \ 			#optional
	fonts-beng \ 				#optional
	fonts-beng-extra \ 			#optional
	#fonts-dejavu-core \ 			#optional
	fonts-deva \ 				#optional
	fonts-deva-extra \ 			#optional
	#fonts-droid-fallback \ 		#optional
	fonts-freefont-ttf \ 			#optional
	fonts-gargi \ 				#optional
	fonts-gubbi \ 				#optional
	fonts-gujr \ 				#optional
	fonts-gujr-extra \ 			#optional
	fonts-guru \ 				#optional
	fonts-guru-extra \ 			#optional
	fonts-indic \ 				#optional
	fonts-kacst \ 				#optional
	fonts-kacst-one \ 			#optional
	fonts-kalapi \ 				#optional
	fonts-khmeros-core \ 			#optional
	fonts-knda \ 				#optional
	fonts-lao \ 				#optional
	fonts-liberation \ 			#optional
	fonts-liberation2 \ 			#optional
	fonts-lklug-sinhala \ 			#optional
	fonts-lohit-beng-assamese \ 		#optional
	fonts-lohit-beng-bengali \ 		#optional
	fonts-lohit-deva \ 			#optional
	fonts-lohit-gujr \ 			#optional
	fonts-lohit-guru \ 			#optional
	fonts-lohit-knda \ 			#optional
	fonts-lohit-mlym \ 			#optional
	fonts-lohit-orya \ 			#optional
	fonts-lohit-taml \ 			#optional
	fonts-lohit-taml-classical \ 		#optional
	fonts-lohit-telu \ 			#optional
	fonts-mlym \ 				#optional
	fonts-nakula \				#optional
	fonts-navilu \ 				#optional
	fonts-noto-cjk \ 			#optional
	fonts-noto-color-emoji \ 		#optional
	#fonts-noto-mono \ 			#optional
	fonts-opensymbol \ 			#optional
	fonts-orya \ 				#optional
	fonts-orya-extra \ 			#optional
	fonts-pagul \ 				#optional
	fonts-sahadeva \ 			#optional
	fonts-samyak-deva \ 			#optional
	fonts-samyak-gujr \ 			#optional
	fonts-samyak-mlym \ 			#optional
	fonts-samyak-taml \ 			#optional
	fonts-sarai \ 				#optional
	fonts-sil-abyssinica \ 			#optional
	fonts-sil-padauk \ 			#optional
	fonts-smc \ 				#optional
	fonts-smc-anjalioldlipi \ 		#optional
	fonts-smc-chilanka \ 			#optional
	fonts-smc-dyuthi \ 			#optional
	fonts-smc-gayathri \ 			#optional
	fonts-smc-karumbi \ 			#optional
	fonts-smc-keraleeyam \ 			#optional
	fonts-smc-manjari \ 			#optional
	fonts-smc-meera \ 			#optional
	fonts-smc-rachana \ 			#optional
	fonts-smc-raghumalayalamsans \ 		#optional
	fonts-smc-suruma \ 			#optional
	fonts-smc-uroob \ 			#optional
	fonts-taml \ 				#optional
	fonts-telu \ 				#optional
	fonts-telu-extra \ 			#optional
	fonts-thai-tlwg \ 			#optional
	fonts-tibetan-machine \ 		#optional
	fonts-tlwg-garuda \ 			#optional
	fonts-tlwg-garuda-ttf \ 		#optional
	fonts-tlwg-kinnari \ 			#optional
	fonts-tlwg-kinnari-ttf \ 		#optional
	fonts-tlwg-laksaman \ 			#optional
	fonts-tlwg-laksaman-ttf \ 		#optional
	fonts-tlwg-loma \ 			#optional
	fonts-tlwg-loma-ttf \ 			#optional
	fonts-tlwg-mono \ 			#optional
	fonts-tlwg-mono-ttf \ 			#optional
	fonts-tlwg-norasi \ 			#optional
	fonts-tlwg-norasi-ttf \ 		#optional
	fonts-tlwg-purisa \ 			#optional
	fonts-tlwg-purisa-ttf \ 		#optional
	fonts-tlwg-sawasdee \ 			#optional
	fonts-tlwg-sawasdee-ttf \ 		#optional
	fonts-tlwg-typewriter \ 		#optional
	fonts-tlwg-typewriter-ttf \ 		#optional
	fonts-tlwg-typist \ 			#optional
	fonts-tlwg-typist-ttf \ 		#optional
	fonts-tlwg-typo \ 			#optional
	fonts-tlwg-typo-ttf \ 			#optional
	fonts-tlwg-umpush \ 			#optional
	fonts-tlwg-umpush-ttf \ 		#optional
	fonts-tlwg-waree \ 			#optional
	fonts-tlwg-waree-ttf \ 			#optional
	fonts-ubuntu \ 				#optional
	fonts-urw-base35 \ 			#optional
	fonts-yrsa-rasa \ 			#optional
	#foomatic-db-compressed-ppds \ 		#optional
	#fprintd \ 				#optional
	#friendly-recovery \ 			#optional
	#fuse \ 				#optional
	#fwupd \ 				#optional
	#fwupd-signed \ 			#optional
	gamemode \ 				#optional
	#gcr \ 					#optional
	#gdb \ 					#optional
	#gdbserver \ 				#optional
	#gdisk \ 				#optional
	#gdm3 \ 				#optional
	gedit \ 				#optional
	gedit-common \ 				#optional
	#genisoimage \ 				#optional
	#geoclue-2.0 \ 				#optional
	#ghostscript \ 				#optional
	#ghostscript-x \ 			#optional
	#gir1.2-accountsservice-1.0 \ 		#optional
	#gir1.2-atk-1.0 \ 			#optional
	#gir1.2-atspi-2.0 \ 			#optional
	#gir1.2-dbusmenu-glib-0.4 \ 		#optional
	#gir1.2-dee-1.0 \ 			#optional
	#gir1.2-freedesktop \ 			#optional
	#gir1.2-gck-1 \ 			#optional
	#gir1.2-gcr-3 \ 			#optional
	#gir1.2-gdesktopenums-3.0 \ 		#optional
	#gir1.2-gdkpixbuf-2.0 \ 		#optional
	#gir1.2-gdm-1.0 \ 			#optional
	#gir1.2-geoclue-2.0 \ 			#optional
	#gir1.2-gmenu-3.0 \ 			#optional
	#gir1.2-gnomebluetooth-1.0 \ 		#optional
	#gir1.2-gnomedesktop-3.0 \ 		#optional
	#gir1.2-goa-1.0 \ 			#optional
	#gir1.2-graphene-1.0 \ 			#optional
	#gir1.2-gstreamer-1.0 \ 		#optional
	#gir1.2-gtk-3.0 \ 			#optional
	#gir1.2-gtksource-4 \ 			#optional
	#gir1.2-gweather-3.0 \ 			#optional
	#gir1.2-ibus-1.0 \ 			#optional
	#gir1.2-javascriptcoregtk-4.0 \ 	#optional
	#gir1.2-json-1.0 \ 			#optional
	#gir1.2-mutter-6 \ 			#optional
	#gir1.2-nm-1.0 \ 			#optional
	#gir1.2-nma-1.0 \ 			#optional
	#gir1.2-notify-0.7 \ 			#optional
	#gir1.2-packagekitglib-1.0 \ 		#optional
	#gir1.2-pango-1.0 \			#optional
	#gir1.2-peas-1.0 \ 			#optional
	#gir1.2-polkit-1.0 \ 			#optional
	#gir1.2-rsvg-2.0 \ 			#optional
	#gir1.2-secret-1 \ 			#optional
	#gir1.2-snapd-1 \ 			#optional
	#gir1.2-soup-2.4 \ 			#optional
	#gir1.2-unity-5.0 \ 			#optional
	#gir1.2-upowerglib-1.0 \ 		#optional
	#gir1.2-vte-2.91 \ 			#optional
	#gir1.2-webkit2-4.0 \ 			#optional
	#gir1.2-wnck-3.0 \ 			#optional
	git \ 					#optional
	git-man \ 				#optional
	#gjs \ 					#optional
	#gkbd-capplet \ 			#optional
	#glib-networking \ 			#optional
	#glib-networking-common \ 		#optional
	#glib-networking-services \ 		#optional
	gnome-accessibility-themes \ 		#optional
	gnome-bluetooth \ 			#optional
	gnome-calculator \ 			#optional
	gnome-characters \ 			#optional
	gnome-control-center \ 			#optional
	gnome-control-center-data \ 		#optional
	gnome-control-center-faces \ 		#optional
	gnome-desktop3-data \ 			#optional
	gnome-disk-utility \ 			#optional
	gnome-font-viewer \ 			#optional
	gnome-getting-started-docs \ 		#optional
	gnome-initial-setup \ 			#optional
	gnome-keyring \ 			#optional
	gnome-keyring-pkcs11 \ 			#optional
	gnome-logs \ 				#optional
	gnome-menus \ 				#optional
	gnome-online-accounts \ 		#optional
	gnome-power-manager \ 			#optional
	gnome-screenshot \ 			#optional
	gnome-session-bin \ 			#optional
	gnome-session-canberra \ 		#optional
	gnome-session-common \ 			#optional
	gnome-settings-daemon \ 		#optional
	gnome-settings-daemon-common \ 		#optional
	gnome-shell \ 				#optional
	gnome-shell-common \ 			#optional
	gnome-shell-extension-appindicator \ 	#optional
	gnome-shell-extension-desktop-icons \	#optional
	gnome-shell-extension-ubuntu-dock \ 	#optional
	gnome-startup-applications \ 		#optional
	gnome-system-monitor \ 			#optional
	gnome-terminal \ 			#optional
	gnome-terminal-data \ 			#optional
	gnome-themes-extra \ 			#optional
	gnome-themes-extra-data \ 		#optional
	gnome-user-docs \ 			#optional
	#gnupg \ 				#optional
	#gnupg-l10n \ 				#optional
	#gnupg-utils \ 				#optional
	#gpg \ 					#optional
	#gpg-agent \ 				#optional
	#gpgconf \ 				#optional
	#gpgsm \ 				#optional
	#gpg-wks-client \ 			#optional
	#gpg-wks-server \ 			#optional
	#grub2-common \ 			#optional
	#grub-common \ 				#optional
	#grub-efi-amd64-bin \ 			#optional
	#grub-efi-amd64-signed \ 		#optional
	#grub-gfxpayload-lists \ 		#optional
	#grub-pc \ 				#optional
	#grub-pc-bin \ 				#optional
	#gsettings-desktop-schemas \ 		#optional
	#gsettings-ubuntu-schemas \ 		#optional
	#gstreamer1.0-alsa \ 			#optional
	#gstreamer1.0-clutter-3.0 \ 		#optional
	#gstreamer1.0-gl \ 			#optional
	#gstreamer1.0-packagekit \ 		#optional
	#gstreamer1.0-plugins-base \ 		#optional
	#gstreamer1.0-plugins-base-apps \ 	#optional
	#gstreamer1.0-plugins-good \ 		#optional
	#gstreamer1.0-pulseaudio \ 		#optional
	#gstreamer1.0-tools \ 			#optional
	#gstreamer1.0-x \ 			#optional
	#gtk2-engines-murrine \ 		#optional
	#gtk2-engines-pixbuf \ 			#optional
	#gtk-update-icon-cache \ 		#optional
	#gvfs \ 				#optional
	#gvfs-backends \ 			#optional
	#gvfs-bin \ 				#optional
	#gvfs-common \ 				#optional
	#gvfs-daemons \ 			#optional
	#gvfs-fuse \ 				#optional
	#gvfs-libs \ 				#optional
	#hdparm \ 				#optional
	#hicolor-icon-theme \ 			#optional
	#humanity-icon-theme \ 			#optional
	#ibus \ 				#optional
	#ibus-data \ 				#optional
	#ibus-gtk \ 				#optional
	#ibus-gtk3 \ 				#optional
	#ibus-table \ 				#optional
	#iio-sensor-proxy \ 			#optional
	#im-config \ 				#optional
	#initramfs-tools \ 			#optional
	#initramfs-tools-bin \ 			#optional
	#initramfs-tools-core \ 		#optional
	#inputattach \ 				#optional
	#ippusbxd \ 				#optional
	#iptables \ 				#optional
	#iputils-tracepath \ 			#optional
	#irqbalance \ 				#optional
	#iso-codes \ 				#optional
	#iucode-tool \ 				#optional
	#iw \ 					#optional
	#kerneloops \ 				#optional
	#klibc-utils \ 				#optional
	#krb5-locales \ 			#optional
	#language-pack-en \ 			#optional
	#language-pack-en-base \ 		#optional
	#language-pack-gnome-en \ 		#optional
	#language-pack-gnome-en-base \ 		#optional
	#language-selector-common \ 		#optional
	#language-selector-gnome \ 		#optional
	#laptop-detect \ 			#optional
	#libaa1 \ 				#optional
	#libaccountsservice0 \ 			#optional
	#libamtk-5-0 \ 				#optional
	#libamtk-5-common \ 			#optional
	#libao4 \ 				#optional
	#libao-common \ 			#optional
	#libappindicator3-1 \ 			#optional
	#libappstream4 \ 			#optional
	#libarchive13 \ 			#optional
	#libasn1-8-heimdal \ 			#optional
	#libasound2 \ 				#optional
	#libasound2-data \ 			#optional
	#libasound2-plugins \ 			#optional
	#libaspell15 \ 				#optional
	#libassuan0 \ 				#optional
	#libasyncns0 \ 				#optional
	#libatasmart4 \ 			#optional
	#libatk1.0-0 \ 				#optional
	#libatk1.0-data \ 			#optional
	#libatk-adaptor \ 			#optional
	#libatk-bridge2.0-0 \ 			#optional
	#libatkmm-1.6-1v5 \ 			#optional
	#libatopology2 \ 			#optional
	#libatspi2.0-0 \ 			#optional
	#libauthen-sasl-perl \ 			#optional
	#libavahi-client3 \ 			#optional
	#libavahi-common3 \ 			#optional
	#libavahi-common-data \ 		#optional
	#libavahi-core7 \ 			#optional
	#libavahi-glib1 \ 			#optional
	#libavc1394-0 \ 			#optional
	#libbabeltrace1 \ 			#optional
	#libblockdev2 \ 			#optional
	#libblockdev-crypto2 \ 			#optional
	#libblockdev-fs2 \ 			#optional
	#libblockdev-loop2 \ 			#optional
	#libblockdev-part2 \ 			#optional
	#libblockdev-part-err2 \ 		#optional
	#libblockdev-swap2 \ 			#optional
	#libblockdev-utils2 \ 			#optional
	#libbluetooth3 \ 			#optional
	#libboost-thread1.71.0 \ 		#optional
	#libbrlapi0.7 \ 			#optional
	#libbrotli1 \ 				#optional
	#libc6-dbg \ 				#optional
	#libcaca0 \ 				#optional
	#libcairo2 \ 				#optional
	#libcairo-gobject2 \ 			#optional
	#libcairo-gobject-perl \ 		#optional
	#libcairomm-1.0-1v5 \ 			#optional
	#libcairo-perl \ 			#optional
	#libcamel-1.2-62 \ 			#optional
	#libcanberra0 \ 			#optional
	#libcanberra-gtk3-0 \             	#optional
	#libcanberra-gtk3-module \ 		#optional
	#libcanberra-pulse \ 			#optional
	#libcbor0.6 \ 				#optional
	#libcc1-0 \ 				#optional
	#libcdio18 \ 				#optional
	#libcdio-cdda2 \ 			#optional
	#libcdio-paranoia2 \ 			#optional
	#libcdparanoia0 \ 			#optional
	#libcheese8 \ 				#optional
	#libcheese-gtk25 \ 			#optional
	#libclutter-1.0-0 \ 			#optional
	#libclutter-1.0-common \ 		#optional
	#libclutter-gst-3.0-0 \ 		#optional
	#libclutter-gtk-1.0-0 \ 		#optional
	#libcogl20 \ 				#optional
	#libcogl-common \ 			#optional
	#libcogl-pango20 \ 			#optional
	#libcogl-path20 \ 			#optional
	#libcolord2 \ 				#optional
	#libcolord-gtk1 \ 			#optional
	#libcolorhug2 \ 			#optional
	#libcrack2 \ 				#optional
	#libcue2 \ 				#optional
	#libcups2 \ 				#optional
	#libcupsfilters1 \ 			#optional
	#libcupsimage2 \ 			#optional
	#libcurl3-gnutls \ 			#optional
	#libdaemon0 \ 				#optional
	#libdata-dump-perl \ 			#optional
	#libdatrie1 \ 				#optional
	#libdbus-glib-1-2 \ 			#optional
	#libdbusmenu-glib4 \ 			#optional
	#libdbusmenu-gtk3-4 \ 			#optional
	#libdconf1 \ 				#optional
	#libdee-1.0-4 \ 			#optional
	#libdjvulibre21 \ 			#optional
	#libdjvulibre-text \ 			#optional
	#libdotconf0 \ 				#optional
	#libdpkg-perl \ 			#optional
	#libdrm2 \ 				#optional
	#libdrm-amdgpu1 \ 			#optional
	#libdrm-common \ 			#optional
	#libdrm-intel1 \ 			#optional
	#libdrm-nouveau2 \ 			#optional
	#libdrm-radeon1 \ 			#optional
	#libdv4 \ 				#optional
	#libdw1 \ 				#optional
	#libebackend-1.2-10 \ 			#optional
	#libebook-1.2-20 \ 			#optional
	#libebook-contacts-1.2-3 \ 		#optional
	#libecal-2.0-1 \ 			#optional
	#libedata-book-1.2-26 \ 		#optional
	#libedata-cal-2.0-1 \ 			#optional
	#libedataserver-1.2-24 \ 		#optional
	#libedataserverui-1.2-2 \ 		#optional
	#libedit2 \ 				#optional
	#libefiboot1 \ 				#optional
	#libefivar1 \ 				#optional
	#libegl1 \ 				#optional
	#libegl-mesa0 \ 			#optional
	#libenchant-2-2 \ 			#optional
	#libencode-locale-perl \ 		#optional
	#libepoxy0 \ 				#optional
	#liberror-perl \ 			#optional
	#libespeak-ng1 \ 			#optional
	#libevdev2 \ 				#optional
	#libevdocument3-4 \ 			#optional
	#libevview3-3 \ 			#optional
	#libexempi8 \ 				#optional
	#libexif12 \ 				#optional
	#libexiv2-27 \ 				#optional
	#libextutils-depends-perl \ 		#optional
	#libextutils-pkgconfig-perl \ 		#optional
	#libfftw3-single3 \ 			#optional
	#libfido2-1 \ 				#optional
	#libfile-basedir-perl \ 		#optional
	#libfile-desktopentry-perl \ 		#optional
	#libfile-fcntllock-perl \ 		#optional
	#libfile-listing-perl \ 		#optional
	#libfile-mimeinfo-perl \ 		#optional
	#libflac8 \ 				#optional
	#libfont-afm-perl \ 			#optional
	#libfontconfig1 \ 			#optional
	#libfontembed1 \ 			#optional
	#libfontenc1 \ 				#optional
	#libfprint-2-2 \ 			#optional
	#libfreetype6 \ 			#optional
	#libfuse2 \ 				#optional
	#libfwupd2 \ 				#optional
	#libfwupdplugin1 \ 			#optional
	#libgail18 \ 				#optional
	#libgail-common \ 			#optional
	#libgamemode0 \ 			#optional
	#libgamemodeauto0 \ 			#optional
	#libgbm1 \ 				#optional
	#libgcab-1.0-0 \ 			#optional
	#libgck-1-0 \ 				#optional
	#libgcr-base-3-1 \			#optional
	#libgcr-ui-3-1 \ 			#optional
	#libgd3 \ 				#optional
	#libgdata22 \ 				#optional
	#libgdata-common \ 			#optional
	#libgdbm6 \ 				#optional
	#libgdbm-compat4 \ 			#optional
	#libgdk-pixbuf2.0-0 \ 			#optional
	#libgdk-pixbuf2.0-bin \ 		#optional
	#libgdk-pixbuf2.0-common \ 		#optional
	#libgdm1 \ 				#optional
	#libgee-0.8-2 \ 			#optional
	#libgeoclue-2-0 \ 			#optional
	#libgeocode-glib0 \ 			#optional
	#libgexiv2-2 \ 				#optional
	#libgif7 \ 				#optional
	#libgjs0g \ 				#optional
	#libgl1 \ 				#optional
	#libgl1-mesa-dri \ 			#optional
	#libglapi-mesa \ 			#optional
	#libgles2 \ 				#optional
	#libglib2.0-bin \ 			#optional
	#libglibmm-2.4-1v5 \ 			#optional
	#libglib-object-introspection-perl \ 	#optional
	#libglib-perl \ 			#optional
	#libglu1-mesa \ 			#optional
	#libglvnd0 \ 				#optional
	#libglx0 \ 				#optional
	#libglx-mesa0 \ 			#optional
	#libgnome-autoar-0-0 \ 			#optional
	#libgnome-bluetooth13 \ 		#optional
	#libgnome-desktop-3-19 \ 		#optional
	#libgnomekbd8 \ 			#optional
	#libgnomekbd-common \ 			#optional
	#libgnome-menu-3-0 \ 			#optional
	#libgoa-1.0-0b \ 			#optional
	#libgoa-1.0-common \ 			#optional
	#libgoa-backend-1.0-1 \ 		#optional
	#libgomp1 \ 				#optional
	#libgpgme11 \ 				#optional
	#libgphoto2-6 \ 			#optional
	#libgphoto2-l10n \ 			#optional
	#libgphoto2-port12 \ 			#optional
	#libgpm2 \ 				#optional
	#libgraphene-1.0-0 \ 			#optional
	#libgraphite2-3 \ 			#optional
	#libgs9 \ 				#optional
	#libgs9-common \ 			#optional
	#libgsf-1-114 \ 			#optional
	#libgsf-1-common \ 			#optional
	#libgsound0 \ 				#optional
	#libgspell-1-2 \ 			#optional
	#libgspell-1-common \ 			#optional
	#libgssapi3-heimdal \ 			#optional
	#libgssapi-krb5-2 \ 			#optional
	#libgssdp-1.2-0 \ 			#optional
	#libgstreamer1.0-0 \ 			#optional
	#libgstreamer-gl1.0-0 \ 		#optional
	#libgstreamer-plugins-base1.0-0 \ 	#optional
	#libgtk2.0-0 \ 				#optional
	#libgtk2.0-bin \ 			#optional
	#libgtk2.0-common \ 			#optional
	#libgtk-3-0 \ 				#optional
	#libgtk-3-bin \ 			#optional
	#libgtk-3-common \ 			#optional
	#libgtk3-perl \ 			#optional
	#libgtkmm-3.0-1v5 \ 			#optional
	#libgtksourceview-4-0 \ 		#optional
	#libgtksourceview-4-common \ 		#optional
	#libgtop-2.0-11 \ 			#optional
	#libgtop2-common \ 			#optional
	#libgudev-1.0-0 \ 			#optional
	#libgupnp-1.2-0 \ 			#optional
	#libgupnp-av-1.0-2 \ 			#optional
	#libgupnp-dlna-2.0-3 \ 			#optional
	#libgusb2 \ 				#optional
	#libgweather-3-16 \ 			#optional
	#libgweather-common \ 			#optional
	#libgxps2 \ 				#optional
	#libhandy-0.0-0 \ 			#optional
	#libharfbuzz0b \ 			#optional
	#libharfbuzz-icu0 \ 			#optional
	#libhcrypto4-heimdal \ 			#optional
	#libheimbase1-heimdal \ 		#optional
	#libheimntlm0-heimdal \ 		#optional
	#libhtml-format-perl \ 			#optional
	#libhtml-form-perl \ 			#optional
	#libhtml-parser-perl \ 			#optional
	#libhtml-tagset-perl \ 			#optional
	#libhtml-tree-perl \ 			#optional
	#libhttp-cookies-perl \ 		#optional
	#libhttp-daemon-perl \ 			#optional
	#libhttp-date-perl \ 			#optional
	#libhttp-message-perl \ 		#optional
	#libhttp-negotiate-perl \ 		#optional
	#libhunspell-1.7-0 \ 			#optional
	#libhx509-5-heimdal \ 			#optional
	#libhyphen0 \ 				#optional
	#libibus-1.0-5 \ 			#optional
	#libical3 \ 				#optional
	#libice6 \ 				#optional
	#libidn11 \ 				#optional
	#libiec61883-0 \ 			#optional
	#libieee1284-3 \ 			#optional
	#libijs-0.35 \ 				#optional
	#libimobiledevice6 \ 			#optional
	#libinput10 \ 				#optional
	#libinput-bin \ 			#optional
	#libio-html-perl \ 			#optional
	#libio-socket-ssl-perl \ 		#optional
	#libio-stringy-perl \ 			#optional
	#libip6tc2 \ 				#optional
	#libipc-system-simple-perl \ 		#optional
	#libisl22 \ 				#optional
	#libiw30 \ 				#optional
	#libjack-jackd2-0 \ 			#optional
	#libjansson4 \ 				#optional	
	#libjavascriptcoregtk-4.0-18 \ 		#optional
	#libjbig0 \ 				#optional
	#libjbig2dec0 \ 			#optional
	#libjpeg8 \ 				#optional
	#libjpeg-turbo8 \ 			#optional
	#libjson-glib-1.0-0 \ 			#optional
	#libjson-glib-1.0-common \ 		#optional
	#libk5crypto3 \ 			#optional
	#libkeyutils1 \ 			#optional
	#libklibc \ 				#optional
	#libkpathsea6 \ 			#optional
	#libkrb5-26-heimdal \ 			#optional
	#libkrb5-3 \ 				#optional
	#libkrb5support0 \ 			#optional
	#libksba8 \ 				#optional
	#liblcms2-2 \ 				#optional
	#liblcms2-utils \ 			#optional
	#libldap-2.4-2 \ 			#optional
	#libldap-common \ 			#optional
	#libldb2 \ 				#optional
	#libllvm10 \ 				#optional
	#libllvm9 \ 				#optional
	#liblmdb0 \ 				#optional
	#liblouis20 \ 				#optional
	#liblouis-data \ 			#optional
	#liblouisutdml9 \ 			#optional
	#liblouisutdml-bin \ 			#optional
	#liblouisutdml-data \ 			#optional
	#libltdl7 \ 				#optional
	#liblwp-mediatypes-perl \ 		#optional
	#liblwp-protocol-https-perl \ 		#optional
	#liblzo2-2 \ 				#optional
	#libmailtools-perl \ 			#optional
	#libmaxminddb0 \ 			#optional
	#libmbim-glib4 \ 			#optional
	#libmbim-proxy \ 			#optional
	#libmediaart-2.0-0 \ 			#optional
	#libmm-glib0 \ 				#optional
	#libmozjs-68-0 \ 			#optional
	#libmp3lame0 \ 				#optional
	#libmpfr6 \ 				#optional
	#libmpg123-0 \ 				#optional
	#libmtdev1 \ 				#optional
	#libmtp9 \ 				#optional
	#libmtp-common \ 			#optional
	#libmtp-runtime \ 			#optional
	#libmutter-6-0 \ 			#optional
	#libmysqlclient21 \ 			#optional
	#libnautilus-extension1a \ 		#optional
	#libndp0 \ 				#optional
	#libnet-dbus-perl \ 			#optional
	#libnetfilter-conntrack3 \ 		#optional
	#libnet-http-perl \ 			#optional
	#libnet-smtp-ssl-perl \ 		#optional
	#libnet-ssleay-perl \ 			#optional
	#libnfs13 \ 				#optional
	#libnftnl11 \ 				#optional
	#libnghttp2-14 \ 			#optional
	#libnl-3-200 \ 				#optional
	#libnl-genl-3-200 \ 			#optional
	#libnl-route-3-200 \ 			#optional
	#libnm0 \ 				#optional
	#libnma0 \ 				#optional
	#libnotify4 \ 				#optional
	#libnotify-bin \ 			#optional
	#libnpth0 \ 				#optional
	#libnspr4 \ 				#optional
	#libnss3 \ 				#optional
	#libnss-mdns \ 				#optional
	#libntfs-3g883 \ 			#optional
	#libnuma1 \ 				#optional
	#libnvpair1linux \ 			#optional
	#libogg0 \ 				#optional
	#libopenjp2-7 \ 			#optional
	#libopus0 \ 				#optional
	#liborc-0.4-0 \ 			#optional
	#libpackagekit-glib2-18 \ 		#optional
	#libpam-fprintd \ 			#optional
	#libpam-gnome-keyring \ 		#optional
	#libpango-1.0-0 \ 			#optional
	#libpangocairo-1.0-0 \ 			#optional
	#libpangoft2-1.0-0 \ 			#optional
	#libpangomm-1.4-1v5 \ 			#optional
	#libpangoxft-1.0-0 \ 			#optional
	#libpaper1 \ 				#optional
	#libpaper-utils \ 			#optional
	#libparted2 \ 				#optional
	#libparted-fs-resize0 \ 		#optional
	#libpcap0.8 \ 				#optional
	#libpcaudio0 \ 				#optional
	#libpci3 \ 				#optional
	#libpciaccess0 \ 			#optional
	#libpcre2-32-0 \ 			#optional
	#libpcsclite1 \ 			#optional
	#libpeas-1.0-0 \ 			#optional
	#libpeas-common \ 			#optional
	#libperl5.30 \ 				#optional
	#libphonenumber7 \ 			#optional
	#libpipeline1 \ 			#optional
	#libpixman-1-0 \ 			#optional
	#libpkcs11-helper1 \ 			#optional
	#libplist3 \ 				#optional
	#libplymouth5 \ 			#optional
	#libpng16-16 \ 				#optional
	#libpolkit-agent-1-0 \ 			#optional
	#libpolkit-gobject-1-0 \ 		#optional
	#libpoppler97 \ 			#optional
	#libpoppler-cpp0v5 \ 			#optional
	#libpoppler-glib8 \ 			#optional
	#libprotobuf17 \ 			#optional
	#libproxy1-plugin-gsettings \ 		#optional
	#libproxy1-plugin-networkmanager \ 	#optional
	#libproxy1v5 \ 				#optional
	#libpsl5 \ 				#optional
	#libpulse0 \ 				#optional
	#libpulsedsp \ 				#optional
	#libpulse-mainloop-glib0 \ 		#optional
	#libpwquality1 \ 			#optional
	#libpwquality-common \ 			#optional
	#libpython3.8 \ 			#optional
	#libqmi-glib5 \ 			#optional
	#libqmi-proxy \ 			#optional
	#libqpdf26 \ 				#optional	
	#libraw1394-11 \ 			#optional
	#librest-0.7-0 \ 			#optional
	#libroken18-heimdal \ 			#optional
	#librsvg2-2 \ 				#optional
	#librsvg2-common \ 			#optional
	#librtmp1 \ 				#optional
	#librygel-core-2.6-2 \ 			#optional
	#librygel-db-2.6-2 \ 			#optional
	#librygel-renderer-2.6-2 \ 		#optional
	#librygel-server-2.6-2 \ 		#optional
	#libsamplerate0 \ 			#optional
	libsane \ 				#optional
	libsane-common \ 			#optional
	#libsane-hpaio \ 			#optional
	#libsasl2-modules \ 			#optional
	#libsbc1 \ 				#optional
	#libsecret-1-0 \ 			#optional
	#libsecret-common \ 			#optional
	#libsensors5 \ 				#optional
	#libsensors-config \ 			#optional
	#libshout3 \ 				#optional
	#libsigc++-2.0-0v5 \ 			#optional
	#libsm6 \ 				#optional
	#libsmbclient \ 			#optional
	#libsmbios-c2 \ 			#optional
	#libsnapd-glib1 \ 			#optional
	#libsndfile1 \ 				#optional
	#libsnmp35 \ 				#optional
	#libsnmp-base \ 			#optional
	#libsonic0 \ 				#optional
	#libsoup2.4-1 \ 			#optional
	#libsoup-gnome2.4-1 \ 			#optional
	#libsoxr0 \ 				#optional
	#libspectre1 \ 				#optional
	#libspeechd2 \ 				#optional
	#libspeex1 \ 				#optional
	#libspeexdsp1 \ 			#optional
	#libssh-4 \ 				#optional
	#libstartup-notification0 \ 		#optional
	#libstemmer0d \ 			#optional
	#libsynctex2 \ 				#optional
	#libsysmetrics1 \ 			#optional
	#libtag1v5 \ 				#optional
	#libtag1v5-vanilla \ 			#optional
	#libtalloc2 \ 				#optional
	#libtdb1 \ 				#optional
	#libteamdctl0 \ 			#optional
	#libtepl-4-0 \ 				#optional
	#libtevent0 \ 				#optional
	#libthai0 \ 				#optional
	#libthai-data \ 			#optional
	#libtheora0 \ 				#optional
	#libtie-ixhash-perl \ 			#optional
	#libtiff5 \ 				#optional
	#libtimedate-perl \ 			#optional
	#libtotem-plparser18 \ 			#optional
	#libtotem-plparser-common \ 		#optional
	#libtracker-control-2.0-0 \ 		#optional
	#libtracker-miner-2.0-0 \ 		#optional
	#libtracker-sparql-2.0-0 \ 		#optional
	#libtry-tiny-perl \ 			#optional
	#libtss2-esys0 \ 			#optional
	#libtwolame0 \ 				#optional
	#libu2f-udev \ 				#optional
	#libuchardet0 \ 			#optional
	#libudisks2-0 \ 			#optional
	#libunity9 \ 				#optional
	#libunity-protocol-private0 \ 		#optional
	#libunity-scopes-json-def-desktop \ 	#optional
	#libunwind8 \ 				#optional
	#libupower-glib3 \ 			#optional
	#liburi-perl \ 				#optional
	#libusb-1.0-0 \ 			#optional
	#libusbmuxd6 \ 				#optional
	#libuutil1linux \ 			#optional
	#libuv1 \ 				#optional
	#libv4l-0 \ 				#optional
	#libv4lconvert0 \ 			#optional
	#libvisual-0.4-0 \ 			#optional
	#libvolume-key1 \ 			#optional
	#libvorbis0a \ 				#optional
	#libvorbisenc2 \ 			#optional
	#libvorbisfile3 \ 			#optional
	#libvpx6 \ 				#optional
	#libvte-2.91-0 \ 			#optional
	#libvte-2.91-common \ 			#optional
	#libvulkan1 \ 				#optional
	#libwacom2 \ 				#optional
	#libwacom-bin \ 			#optional
	#libwacom-common \ 			#optional
	#libwavpack1 \ 				#optional
	#libwayland-client0 \ 			#optional
	#libwayland-cursor0 \ 			#optional
	#libwayland-egl1 \ 			#optional
	#libwayland-server0 \ 			#optional
	#libwbclient0 \ 			#optional
	#libwebkit2gtk-4.0-37 \ 		#optional
	#libwebp6 \ 				#optional
	#libwebpdemux2 \ 			#optional
	#libwebrtc-audio-processing1 \ 		#optional
	#libwhoopsie0 \ 			#optional
	#libwhoopsie-preferences0 \ 		#optional
	#libwind0-heimdal \ 			#optional
	#libwmf0.2-7 \ 				#optional
	#libwmf0.2-7-gtk \ 			#optional
	#libwnck-3-0 \ 				#optional
	#libwnck-3-common \ 			#optional
	#libwoff1 \ 				#optional
	#libwrap0 \ 				#optional
	#libwww-perl \ 				#optional
	#libwww-robotrules-perl \ 		#optional
	#libx11-6 \ 				#optional
	#libx11-data \ 				#optional
	#libx11-protocol-perl \ 		#optional
	#libx11-xcb1 \ 				#optional
	#libxatracker2 \ 			#optional
	#libxau6 \ 				#optional
	#libxaw7 \ 				#optional
	#libxcb1 \ 				#optional
	#libxcb-dri2-0 \ 			#optional
	#libxcb-dri3-0 \ 			#optional
	#libxcb-glx0 \ 				#optional
	#libxcb-icccm4 \ 			#optional
	#libxcb-present0 \ 			#optional
	#libxcb-randr0 \ 			#optional
	#libxcb-render0 \ 			#optional
	#libxcb-res0 \ 				#optional
	#libxcb-shape0 \ 			#optional
	#libxcb-shm0 \ 				#optional
	#libxcb-sync1 \ 			#optional
	#libxcb-xfixes0 \ 			#optional
	#libxcb-xkb1 \ 				#optional
	#libxcb-xv0 \ 				#optional
	#libxcomposite1 \ 			#optional
	#libxcursor1 \ 				#optional
	#libxdamage1 \ 				#optional
	#libxdmcp6 \ 				#optional
	#libxext6 \ 				#optional
	#libxfixes3 \ 				#optional
	#libxfont2 \ 				#optional
	#libxft2 \ 				#optional
	#libxi6 \ 				#optional
	#libxinerama1 \ 			#optional
	#libxkbcommon0 \ 			#optional
	#libxkbcommon-x11-0 \ 			#optional
	#libxkbfile1 \ 				#optional
	#libxklavier16 \ 			#optional
	#libxmlb1 \ 				#optional
	#libxml-parser-perl \ 			#optional
	#libxml-twig-perl \ 			#optional
	#libxml-xpathengine-perl \ 		#optional
	#libxmu6 \ 				#optional
	#libxmuu1 \ 				#optional
	#libxpm4 \ 				#optional
	#libxrandr2 \ 				#optional
	#libxrender1 \ 				#optional
	#libxres1 \ 				#optional
	#libxshmfence1 \ 			#optional
	#libxslt1.1 \ 				#optional
	#libxss1 \ 				#optional
	#libxt6 \ 				#optional
	#libxtst6 \ 				#optional
	#libxv1 \ 				#optional
	#libxvmc1 \ 				#optional
	#libxxf86dga1 \ 			#optional
	#libxxf86vm1 \ 				#optional
	#libyelp0 \ 				#optional
	#libzfs2linux \ 			#optional
	#libzpool2linux \ 			#optional
	#linux-base \ 				#optional
	#linux-firmware \ 			#optional
	#linux-generic-hwe-20.04 \ 		#optional
	#linux-headers-5.4.0-42 \ 		#optional
	#linux-headers-5.4.0-42-generic \ 	#optional
	#linux-headers-5.4.0-48 \ 		#optional
	#linux-headers-5.4.0-48-generic \ 	#optional
	#linux-headers-generic-hwe-20.04 \ 	#optional
	#linux-image-5.4.0-42-generic \ 	#optional
	#linux-image-5.4.0-48-generic \ 	#optional
	#linux-image-generic-hwe-20.04 \ 	#optional
	#linux-modules-5.4.0-42-generic \ 	#optional
	#linux-modules-5.4.0-48-generic \ 	#optional
	#linux-modules-extra-5.4.0-42-generic \ #optional
	#linux-modules-extra-5.4.0-48-generic \ #optional
	#linux-sound-base \ 			#optional
	#lshw \ 				#optional
	#ltrace \ 				#optional
	#lz4 \ 					#optional
	#memtest86+ \ 				#optional
	#mesa-vulkan-drivers \ 			#optional
	#mobile-broadband-provider-info \ 	#optional
	#modemmanager \ 			#optional
	#mokutil \ 				#optional
	#mousetweaks \ 				#optional
	#mscompress \ 				#optional
	#mtools \ 				#optional
	#mtr-tiny \ 				#optional
	#mutter \	 			#optional
	#mutter-common \ 			#optional
	#mysql-common \ 			#optional
	#nautilus \ 				#optional
	#nautilus-data \ 			#optional
	#nautilus-extension-gnome-terminal \ 	#optional
	#nautilus-sendto \ 			#optional
	#nautilus-share \ 			#optional
	#network-manager \ 			#optional
	#network-manager-gnome \ 		#optional
	#network-manager-openvpn \ 		#optional
	#network-manager-openvpn-gnome \ 	#optional
	#network-manager-pptp \ 		#optional
	#network-manager-pptp-gnome \ 		#optional
	#ntfs-3g \ 				#optional
	#openprinting-ppds \			#optional
	#openvpn \ 				#optional
	#orca \ 				#optional
	#p11-kit \ 				#optional
	#p11-kit-modules \ 			#optional
	#packagekit \ 				#optional
	#packagekit-tools \ 			#optional
	#parted \ 				#optional
	#patch \ 				#optional
	#pci.ids \ 				#optional
	#pcmciautils \ 				#optional
	#perl-openssl-defaults \ 		#optional
	#pinentry-curses \ 			#optional
	#pinentry-gnome3 \ 			#optional
	#pkg-config \ 				#optional
	#plymouth \ 				#optional
	#plymouth-label \ 			#optional
	#plymouth-theme-spinner \ 		#optional
	#plymouth-theme-ubuntu-text \ 		#optional
	#policykit-1 \ 				#optional
	#policykit-desktop-privileges \ 	#optional
	#poppler-data \ 			#optional
	#poppler-utils \ 			#optional
	#popularity-contest \ 			#optional
	#powermgmt-base \ 			#optional
	#ppp \ 					#optional
	#pptp-linux \ 				#optional
	printer-driver-brlaser \ 		#optional
	#printer-driver-c2esp \ 		#optional
	printer-driver-foo2zjs \ 		#optional
	printer-driver-foo2zjs-common \ 	#optional
	printer-driver-m2300w \ 		#optional
	#printer-driver-min12xxw \ 		#optional
	#printer-driver-pnm2ppa \ 		#optional
	printer-driver-ptouch \ 		#optional
	#printer-driver-pxljr \ 		#optional
	#printer-driver-sag-gdi \ 		#optional
	printer-driver-splix \ 			#optional
	#psmisc \ 				#optional
	#publicsuffix \ 			#optional
	pulseaudio \ 				#optional
	pulseaudio-module-bluetooth \ 		#optional
	pulseaudio-utils \ 			#optional
	#python3-apport \ 			#optional
	#python3-apt \ 				#optional
	#python3-blinker \ 			#optional
	#python3-brlapi \ 			#optional
	#python3-cairo \ 			#optional
	#python3-certifi \ 			#optional
	#python3-chardet \ 			#optional
	#python3-click \ 			#optional
	#python3-colorama \ 			#optional
	#python3-commandnotfound \ 		#optional
	#python3-cryptography \ 		#optional
	#python3-cups \ 			#optional
	#python3-cupshelpers \ 			#optional
	#python3-dateutil \ 			#optional
	#python3-debconf \ 			#optional
	#python3-debian \ 			#optional
	#python3-distro \ 			#optional
	#python3-distro-info \ 			#optional
	#python3-distupgrade \ 			#optional
	#python3-entrypoints \ 			#optional
	#python3-gdbm \ 			#optional
	#python3-gi-cairo \ 			#optional
	#python3-httplib2 \ 			#optional
	#python3-ibus-1.0 \ 			#optional
	#python3-idna \ 			#optional
	#python3-jwt \ 				#optional
	#python3-keyring \ 			#optional
	#python3-launchpadlib \ 		#optional
	#python3-lazr.restfulclient \ 		#optional
	#python3-lazr.uri \ 			#optional
	#python3-louis \ 			#optional
	#python3-macaroonbakery \ 		#optional
	#python3-oauthlib \ 			#optional
	#python3-problem-report \ 		#optional
	#python3-protobuf \ 			#optional
	#python3-pyatspi \ 			#optional
	#python3-requests \ 			#optional
	#python3-requests-unixsocket \ 		#optional
	#python3-rfc3339 \ 			#optional
	#python3-secretstorage \ 		#optional
	#python3-simplejson \ 			#optional
	#python3-software-properties \ 		#optional
	#python3-speechd \ 			#optional
	#python3-systemd \ 			#optional
	#python3-talloc \ 			#optional
	#python3-tz \ 				#optional
	#python3-update-manager \ 		#optional
	#python3-urllib3 \ 			#optional
	#python3-wadllib \ 			#optional
	#python3-xdg \ 				#optional
	#python3-xkit \ 			#optional
	#python-apt-common \ 			#optional
	#rfkill \ 				#optional
	#rsync \ 				#optional
	#rtkit \ 				#optional
	#rygel \ 				#optional
	#samba-libs \ 				#optional
	sane-utils \ 				#optional
	#sbsigntool \ 				#optional
	#seahorse \ 				#optional
	#secureboot-db \ 			#optional
	#sgml-base \ 				#optional
	#sgml-data \ 				#optional
	#shim \ 				#optional
	#shim-signed \ 				#optional
	#snapd \ 				#optional
	#software-properties-common \ 		#optional
	#software-properties-gtk \ 		#optional
	#sound-icons \ 				#optional
	#sound-theme-freedesktop \ 		#optional
	#speech-dispatcher \ 			#optional
	#speech-dispatcher-audio-plugins \ 	#optional
	#speech-dispatcher-espeak-ng \ 		#optional
	#spice-vdagent \ 			#optional
	#squashfs-tools \ 			#optional
	#ssl-cert \ 				#optional
	#strace \ 				#optional
	#switcheroo-control \ 			#optional
	#system-config-printer \ 		#optional
	#system-config-printer-common \ 	#optional
	#system-config-printer-udev \ 		#optional
	#tcpdump \ 				#optional
	#thermald \ 				#optional
	#tpm-udev \ 				#optional
	#tracker \ 				#optional
	#tracker-extract \ 			#optional
	#tracker-miner-fs \ 			#optional
	#ubuntu-desktop \ 			#optional
	#ubuntu-desktop-minimal \		#optional
	#ubuntu-docs \ 				#optional
	#ubuntu-drivers-common \ 		#optional
	#ubuntu-mono \ 				#optional
	#ubuntu-release-upgrader-core \ 	#optional
	#ubuntu-release-upgrader-gtk \ 		#optional
	#ubuntu-report \ 			#optional
	#ubuntu-session \ 			#optional
	#ubuntu-settings \ 			#optional
	#ubuntu-wallpapers \ 			#optional
	#ubuntu-wallpapers-focal \ 		#optional
	#udisks2 \ 				#optional
	#ufw \ 					#optional
	#unattended-upgrades \ 			#optional
	#unzip \ 				#optional
	#update-inetd \ 			#optional
	#update-manager \ 			#optional
	#update-manager-core \ 			#optional
	#update-notifier \ 			#optional
	#update-notifier-common \ 		#optional
	#upower \ 				#optional
	#usb.ids \ 				#optional
	#usb-modeswitch \ 			#optional
	#usb-modeswitch-data \ 			#optional
	#usbmuxd \ 				#optional
	#usbutils \ 				#optional
	#uuid-runtime \ 			#optional
	#wbritish \ 				#optional
	#whoopsie \ 				#optional
	#whoopsie-preferences \ 		#optional
	#wireless-regdb \ 			#optional
	#wireless-tools \ 			#optional
	#wpasupplicant \ 			#optional
	x11-apps \ 				#optional
	x11-common \ 				#optional
	x11-session-utils \ 			#optional
	x11-utils \ 				#optional
	x11-xkb-utils \ 			#optional
	x11-xserver-utils \ 			#optional
	xauth \ 				#optional
	xbitmaps \ 				#optional
	xbrlapi \ 				#optional
	xcursor-themes \ 			#optional
	#xdg-dbus-proxy \ 			#optional
	#xdg-desktop-portal \ 			#optional
	#xdg-desktop-portal-gtk \ 		#optional
	#xdg-user-dirs-gtk \ 			#optional
	#xdg-utils \ 				#optional
	xfonts-base \ 				#optional
	xfonts-encodings \ 			#optional
	xfonts-scalable \ 			#optional
	xfonts-utils \ 				#optional
	xinit \ 				#optional
	xinput \ 				#optional
	#xml-core \ 				#optional
	xorg \ 					#optional
	xorg-docs-core \ 			#optional
	xserver-common \ 			#optional
	xserver-xephyr \ 			#optional
	xserver-xorg \ 				#optional
	xserver-xorg-core \ 			#optional
	xserver-xorg-input-all \ 		#optional
	xserver-xorg-input-libinput \ 		#optional
	xserver-xorg-input-wacom \ 		#optional
	xserver-xorg-legacy \ 			#optional
	xserver-xorg-video-all \ 		#optional
	xserver-xorg-video-amdgpu \ 		#optional
	xserver-xorg-video-ati \ 		#optional
	xserver-xorg-video-fbdev \ 		#optional
	xserver-xorg-video-intel \ 		#optional
	xserver-xorg-video-nouveau \ 		#optional
	xserver-xorg-video-qxl \ 		#optional
	xserver-xorg-video-radeon \ 		#optional
	xserver-xorg-video-vesa \ 		#optional
	xserver-xorg-video-vmware \ 		#optional
	xul-ext-ubufox \ 			#optional
	#xwayland \ 				#optional
	yaru-theme-gnome-shell \ 		#optional
	yaru-theme-gtk \ 			#optional
	yaru-theme-icon \ 			#optional
	yaru-theme-sound \ 			#optional
	yelp \ 					#optional
	yelp-xsl \ 				#optional
	#zenity \ 				#optional
	#zenity-common \ 			#optional
	#zfs-initramfs \ 			#optional
	#zfsutils-linux \ 			#optional
	#zfs-zed \ 				#optional
	#zip \ 					#optional
	#zsys	 				#optional
sudo apt autoremove

