alias sap="sudo apt purge -y" 
#sap accountsservice 			
#sap acl  					
#sap acpid  				
#sap acpi-support  			
sap adwaita-icon-theme  			
#sap alsa-base  				
#sap alsa-topology-conf  			
#sap alsa-ucm-conf  			
#sap alsa-utils  				
#sap anacron  				
#sap apg  					
#sap apparmor  				
#sap app-install-data-partner  		
#sap apport  				
#sap apport-gtk  				
#sap apport-symptoms  			
#sap appstream  				
#sap apt-config-icons  			
#sap apt-config-icons-hidpi  		
#sap apturl  				
#sap apturl-common  			
#sap aspell  				
#sap aspell-en  				
#sap at-spi2-core  		     	
#sap avahi-autoipd  			
#sap avahi-daemon  			
#sap avahi-utils  				
#sap bluez  				
#sap bluez-cups  				
#sap bluez-obexd  				
#sap bolt  				
sap brltty  				
#sap bubblewrap  				
#sap busybox-initramfs  			
#sap busybox-static  			
#sap cheese-common  			
#sap colord  				
#sap colord-data  				
#sap command-not-found  			
#sap cpp  					
#sap cpp-9  				
#sap cracklib-runtime  			
#sap crda  				
#sap cups  				
#sap cups-browsed  			
#sap cups-bsd  				
#sap cups-client  				
#sap cups-common  				
#sap cups-core-drivers  			
#sap cups-daemon  				
#sap cups-filters  			
#sap cups-filters-core-drivers  		
#sap cups-ipp-utils  			
#sap cups-ppdc  				
#sap cups-server-common  			
#sap dbus-user-session  			
#sap dbus-x11  				
#sap dconf-cli  				
#sap dconf-gsettings-backend  		
#sap dconf-service  			
#sap desktop-file-utils  			
#sap dictionaries-common  			
#sap dirmngr  				
#sap dmz-cursor-theme  			
#sap dnsmasq-base  			
#sap dns-root-data  			
#sap docbook-xml  				
#sap dosfstools  				
#sap ed  					
#sap efibootmgr  				
#sap emacsen-common  			
#sap enchant-2  				
#sap eog  					
#sap espeak-ng-data  			
#sap evince  				
#sap evince-common  			
#sap evolution-data-server  		
#sap evolution-data-server-common  	
#sap file-roller  				
sap firefox  				
sap firefox-locale-en  			
#sap fontconfig  				
#sap fontconfig-config  			
sap fonts-beng  				
sap fonts-beng-extra  			
#sap fonts-dejavu-core  			
sap fonts-deva  				
sap fonts-deva-extra  			
#sap fonts-droid-fallback  		
sap fonts-freefont-ttf  			
sap fonts-gargi  				
sap fonts-gubbi  				
sap fonts-gujr  				
sap fonts-gujr-extra  			
sap fonts-guru  				
sap fonts-guru-extra  			
sap fonts-indic  				
sap fonts-kacst  				
sap fonts-kacst-one  			
sap fonts-kalapi  				
sap fonts-khmeros-core  			
sap fonts-knda  				
sap fonts-lao  				
sap fonts-liberation  			
sap fonts-liberation2  			
sap fonts-lklug-sinhala  			
sap fonts-lohit-beng-assamese  		
sap fonts-lohit-beng-bengali  		
sap fonts-lohit-deva  			
sap fonts-lohit-gujr  			
sap fonts-lohit-guru  			
sap fonts-lohit-knda  			
sap fonts-lohit-mlym  			
sap fonts-lohit-orya  			
sap fonts-lohit-taml  			
sap fonts-lohit-taml-classical  		
sap fonts-lohit-telu  			
sap fonts-mlym  				
sap fonts-nakula 				
sap fonts-navilu  				
sap fonts-noto-cjk  			
#sap fonts-noto-color-emoji  		
#sap fonts-noto-mono  			
#sap fonts-opensymbol  			
sap fonts-orya  				
sap fonts-orya-extra  			
sap fonts-pagul  				
sap fonts-sahadeva  			
sap fonts-samyak-deva  			
sap fonts-samyak-gujr  			
sap fonts-samyak-mlym  			
sap fonts-samyak-taml  			
sap fonts-sarai  				
sap fonts-sil-abyssinica  			
sap fonts-sil-padauk  			
sap fonts-smc  				
sap fonts-smc-anjalioldlipi  		
sap fonts-smc-chilanka  			
sap fonts-smc-dyuthi  			
sap fonts-smc-gayathri  			
sap fonts-smc-karumbi  			
sap fonts-smc-keraleeyam  			
sap fonts-smc-manjari  			
sap fonts-smc-meera  			
sap fonts-smc-rachana  			
sap fonts-smc-raghumalayalamsans  		
sap fonts-smc-suruma  			
sap fonts-smc-uroob  			
sap fonts-taml  				
sap fonts-telu  				
sap fonts-telu-extra  			
sap fonts-thai-tlwg  			
sap fonts-tibetan-machine  		
sap fonts-tlwg-garuda  			
sap fonts-tlwg-garuda-ttf  		
sap fonts-tlwg-kinnari  			
sap fonts-tlwg-kinnari-ttf  		
sap fonts-tlwg-laksaman  			
sap fonts-tlwg-laksaman-ttf  		
sap fonts-tlwg-loma  			
sap fonts-tlwg-loma-ttf  			
sap fonts-tlwg-mono  			
sap fonts-tlwg-mono-ttf  			
sap fonts-tlwg-norasi  			
sap fonts-tlwg-norasi-ttf  		
sap fonts-tlwg-purisa  			
sap fonts-tlwg-purisa-ttf  		
sap fonts-tlwg-sawasdee  			
sap fonts-tlwg-sawasdee-ttf  		
sap fonts-tlwg-typewriter  		
sap fonts-tlwg-typewriter-ttf  		
sap fonts-tlwg-typist  			
sap fonts-tlwg-typist-ttf  		
sap fonts-tlwg-typo  			
sap fonts-tlwg-typo-ttf  			
sap fonts-tlwg-umpush  			
sap fonts-tlwg-umpush-ttf  		
sap fonts-tlwg-waree  			
sap fonts-tlwg-waree-ttf  			
#sap fonts-ubuntu  				
sap fonts-urw-base35  			
sap fonts-yrsa-rasa  			
#sap foomatic-db-compressed-ppds  		
#sap fprintd  				
#sap friendly-recovery  			
#sap fuse  				
#sap fwupd  				
#sap fwupd-signed  			
sap gamemode  				
#sap gcr  					
#sap gdb  					
#sap gdbserver  				
#sap gdisk  				
#sap gdm3  				
sap gedit  				
sap gedit-common  				
#sap genisoimage  				
#sap geoclue-2.0  				
#sap ghostscript  				
#sap ghostscript-x  			
#sap gir1.2-accountsservice-1.0  		
#sap gir1.2-atk-1.0  			
#sap gir1.2-atspi-2.0  			
#sap gir1.2-dbusmenu-glib-0.4  		
#sap gir1.2-dee-1.0  			
#sap gir1.2-freedesktop  			
#sap gir1.2-gck-1  			
#sap gir1.2-gcr-3  			
#sap gir1.2-gdesktopenums-3.0  		
#sap gir1.2-gdkpixbuf-2.0  		
#sap gir1.2-gdm-1.0  			
#sap gir1.2-geoclue-2.0  			
#sap gir1.2-gmenu-3.0  			
#sap gir1.2-gnomebluetooth-1.0  		
#sap gir1.2-gnomedesktop-3.0  		
#sap gir1.2-goa-1.0  			
#sap gir1.2-graphene-1.0  			
#sap gir1.2-gstreamer-1.0  		
#sap gir1.2-gtk-3.0  			
#sap gir1.2-gtksource-4  			
#sap gir1.2-gweather-3.0  			
#sap gir1.2-ibus-1.0  			
#sap gir1.2-javascriptcoregtk-4.0  	
#sap gir1.2-json-1.0  			
#sap gir1.2-mutter-6  			
#sap gir1.2-nm-1.0  			
#sap gir1.2-nma-1.0  			
#sap gir1.2-notify-0.7  			
#sap gir1.2-packagekitglib-1.0  		
#sap gir1.2-pango-1.0 			
#sap gir1.2-peas-1.0  			
#sap gir1.2-polkit-1.0  			
#sap gir1.2-rsvg-2.0  			
#sap gir1.2-secret-1  			
#sap gir1.2-snapd-1  			
#sap gir1.2-soup-2.4  			
#sap gir1.2-unity-5.0  			
#sap gir1.2-upowerglib-1.0  		
#sap gir1.2-vte-2.91  			
#sap gir1.2-webkit2-4.0  			
#sap gir1.2-wnck-3.0  			
sap git  					
sap git-man  				
#sap gjs  					
#sap gkbd-capplet  			
#sap glib-networking  			
#sap glib-networking-common  		
#sap glib-networking-services  		
sap gnome-accessibility-themes  		
sap gnome-bluetooth  			
sap gnome-calculator  			
sap gnome-characters  			
sap gnome-control-center  			
sap gnome-control-center-data  		
sap gnome-control-center-faces  		
sap gnome-desktop3-data  			
sap gnome-disk-utility  			
sap gnome-font-viewer  			
sap gnome-getting-started-docs  		
sap gnome-initial-setup  			
sap gnome-keyring  			
sap gnome-keyring-pkcs11  			
sap gnome-logs  				
sap gnome-menus  				
sap gnome-online-accounts  		
sap gnome-power-manager  			
sap gnome-screenshot  			
sap gnome-session-bin  			
sap gnome-session-canberra  		
sap gnome-session-common  			
sap gnome-settings-daemon  		
sap gnome-settings-daemon-common  		
sap gnome-shell  				
sap gnome-shell-common  			
sap gnome-shell-extension-appindicator  	
sap gnome-shell-extension-desktop-icons 	
sap gnome-shell-extension-ubuntu-dock  	
sap gnome-startup-applications  		
sap gnome-system-monitor  			
sap gnome-terminal  			
sap gnome-terminal-data  			
sap gnome-themes-extra  			
sap gnome-themes-extra-data  		
sap gnome-user-docs  			
#sap gnupg  				
#sap gnupg-l10n  				
#sap gnupg-utils  				
#sap gpg  					
#sap gpg-agent  				
#sap gpgconf  				
#sap gpgsm  				
#sap gpg-wks-client  			
#sap gpg-wks-server  			
#sap grub2-common  			
#sap grub-common  				
#sap grub-efi-amd64-bin  			
#sap grub-efi-amd64-signed  		
#sap grub-gfxpayload-lists  		
#sap grub-pc  				
#sap grub-pc-bin  				
#sap gsettings-desktop-schemas  		
#sap gsettings-ubuntu-schemas  		
#sap gstreamer1.0-alsa  			
#sap gstreamer1.0-clutter-3.0  		
#sap gstreamer1.0-gl  			
#sap gstreamer1.0-packagekit  		
#sap gstreamer1.0-plugins-base  		
#sap gstreamer1.0-plugins-base-apps  	
#sap gstreamer1.0-plugins-good  		
#sap gstreamer1.0-pulseaudio  		
#sap gstreamer1.0-tools  			
#sap gstreamer1.0-x  			
#sap gtk2-engines-murrine  		
#sap gtk2-engines-pixbuf  			
#sap gtk-update-icon-cache  		
#sap gvfs  				
#sap gvfs-backends  			
#sap gvfs-bin  				
#sap gvfs-common  				
#sap gvfs-daemons  			
#sap gvfs-fuse  				
#sap gvfs-libs  				
#sap hdparm  				
#sap hicolor-icon-theme  			
#sap humanity-icon-theme  			
#sap ibus  				
#sap ibus-data  				
#sap ibus-gtk  				
#sap ibus-gtk3  				
#sap ibus-table  				
#sap iio-sensor-proxy  			
#sap im-config  				
#sap initramfs-tools  			
#sap initramfs-tools-bin  			
#sap initramfs-tools-core  		
#sap inputattach  				
#sap ippusbxd  				
#sap iptables  				
#sap iputils-tracepath  			
#sap irqbalance  				
#sap iso-codes  				
#sap iucode-tool  				
#sap iw  					
#sap kerneloops  				
#sap klibc-utils  				
#sap krb5-locales  			
#sap language-pack-en  			
#sap language-pack-en-base  		
#sap language-pack-gnome-en  		
#sap language-pack-gnome-en-base  		
#sap language-selector-common  		
#sap language-selector-gnome  		
#sap laptop-detect  			
#sap libaa1  				
#sap libaccountsservice0  			
#sap libamtk-5-0  				
#sap libamtk-5-common  			
#sap libao4  				
#sap libao-common  			
#sap libappindicator3-1  			
#sap libappstream4  			
#sap libarchive13  			
#sap libasn1-8-heimdal  			
#sap libasound2  				
#sap libasound2-data  			
#sap libasound2-plugins  			
#sap libaspell15  				
#sap libassuan0  				
#sap libasyncns0  				
#sap libatasmart4  			
#sap libatk1.0-0  				
#sap libatk1.0-data  			
#sap libatk-adaptor  			
#sap libatk-bridge2.0-0  			
#sap libatkmm-1.6-1v5  			
#sap libatopology2  			
#sap libatspi2.0-0  			
#sap libauthen-sasl-perl  			
#sap libavahi-client3  			
#sap libavahi-common3  			
#sap libavahi-common-data  		
#sap libavahi-core7  			
#sap libavahi-glib1  			
#sap libavc1394-0  			
#sap libbabeltrace1  			
#sap libblockdev2  			
#sap libblockdev-crypto2  			
#sap libblockdev-fs2  			
#sap libblockdev-loop2  			
#sap libblockdev-part2  			
#sap libblockdev-part-err2  		
#sap libblockdev-swap2  			
#sap libblockdev-utils2  			
#sap libbluetooth3  			
#sap libboost-thread1.71.0  		
#sap libbrlapi0.7  			
#sap libbrotli1  				
#sap libc6-dbg  				
#sap libcaca0  				
#sap libcairo2  				
#sap libcairo-gobject2  			
#sap libcairo-gobject-perl  		
#sap libcairomm-1.0-1v5  			
#sap libcairo-perl  			
#sap libcamel-1.2-62  			
#sap libcanberra0  			
#sap libcanberra-gtk3-0              	
#sap libcanberra-gtk3-module  		
#sap libcanberra-pulse  			
#sap libcbor0.6  				
#sap libcc1-0  				
#sap libcdio18  				
#sap libcdio-cdda2  			
#sap libcdio-paranoia2  			
#sap libcdparanoia0  			
#sap libcheese8  				
#sap libcheese-gtk25  			
#sap libclutter-1.0-0  			
#sap libclutter-1.0-common  		
#sap libclutter-gst-3.0-0  		
#sap libclutter-gtk-1.0-0  		
#sap libcogl20  				
#sap libcogl-common  			
#sap libcogl-pango20  			
#sap libcogl-path20  			
#sap libcolord2  				
#sap libcolord-gtk1  			
#sap libcolorhug2  			
#sap libcrack2  				
#sap libcue2  				
#sap libcups2  				
#sap libcupsfilters1  			
#sap libcupsimage2  			
#sap libcurl3-gnutls  			
#sap libdaemon0  				
#sap libdata-dump-perl  			
#sap libdatrie1  				
#sap libdbus-glib-1-2  			
#sap libdbusmenu-glib4  			
#sap libdbusmenu-gtk3-4  			
#sap libdconf1  				
#sap libdee-1.0-4  			
#sap libdjvulibre21  			
#sap libdjvulibre-text  			
#sap libdotconf0  				
#sap libdpkg-perl  			
#sap libdrm2  				
#sap libdrm-amdgpu1  			
#sap libdrm-common  			
#sap libdrm-intel1  			
#sap libdrm-nouveau2  			
#sap libdrm-radeon1  			
#sap libdv4  				
#sap libdw1  				
#sap libebackend-1.2-10  			
#sap libebook-1.2-20  			
#sap libebook-contacts-1.2-3  		
#sap libecal-2.0-1  			
#sap libedata-book-1.2-26  		
#sap libedata-cal-2.0-1  			
#sap libedataserver-1.2-24  		
#sap libedataserverui-1.2-2  		
#sap libedit2  				
#sap libefiboot1  				
#sap libefivar1  				
#sap libegl1  				
#sap libegl-mesa0  			
#sap libenchant-2-2  			
#sap libencode-locale-perl  		
#sap libepoxy0  				
#sap liberror-perl  			
#sap libespeak-ng1  			
#sap libevdev2  				
#sap libevdocument3-4  			
#sap libevview3-3  			
#sap libexempi8  				
#sap libexif12  				
#sap libexiv2-27  				
#sap libextutils-depends-perl  		
#sap libextutils-pkgconfig-perl  		
#sap libfftw3-single3  			
#sap libfido2-1  				
#sap libfile-basedir-perl  		
#sap libfile-desktopentry-perl  		
#sap libfile-fcntllock-perl  		
#sap libfile-listing-perl  		
#sap libfile-mimeinfo-perl  		
#sap libflac8  				
#sap libfont-afm-perl  			
#sap libfontconfig1  			
#sap libfontembed1  			
#sap libfontenc1  				
#sap libfprint-2-2  			
#sap libfreetype6  			
#sap libfuse2  				
#sap libfwupd2  				
#sap libfwupdplugin1  			
#sap libgail18  				
#sap libgail-common  			
#sap libgamemode0  			
#sap libgamemodeauto0  			
#sap libgbm1  				
#sap libgcab-1.0-0  			
#sap libgck-1-0  				
#sap libgcr-base-3-1 			
#sap libgcr-ui-3-1  			
#sap libgd3  				
#sap libgdata22  				
#sap libgdata-common  			
#sap libgdbm6  				
#sap libgdbm-compat4  			
#sap libgdk-pixbuf2.0-0  			
#sap libgdk-pixbuf2.0-bin  		
#sap libgdk-pixbuf2.0-common  		
#sap libgdm1  				
#sap libgee-0.8-2  			
#sap libgeoclue-2-0  			
#sap libgeocode-glib0  			
#sap libgexiv2-2  				
#sap libgif7  				
#sap libgjs0g  				
#sap libgl1  				
#sap libgl1-mesa-dri  			
#sap libglapi-mesa  			
#sap libgles2  				
#sap libglib2.0-bin  			
#sap libglibmm-2.4-1v5  			
#sap libglib-object-introspection-perl  	
#sap libglib-perl  			
#sap libglu1-mesa  			
#sap libglvnd0  				
#sap libglx0  				
#sap libglx-mesa0  			
#sap libgnome-autoar-0-0  			
#sap libgnome-bluetooth13  		
#sap libgnome-desktop-3-19  		
#sap libgnomekbd8  			
#sap libgnomekbd-common  			
#sap libgnome-menu-3-0  			
#sap libgoa-1.0-0b  			
#sap libgoa-1.0-common  			
#sap libgoa-backend-1.0-1  		
#sap libgomp1  				
#sap libgpgme11  				
#sap libgphoto2-6  			
#sap libgphoto2-l10n  			
#sap libgphoto2-port12  			
#sap libgpm2  				
#sap libgraphene-1.0-0  			
#sap libgraphite2-3  			
#sap libgs9  				
#sap libgs9-common  			
#sap libgsf-1-114  			
#sap libgsf-1-common  			
#sap libgsound0  				
#sap libgspell-1-2  			
#sap libgspell-1-common  			
#sap libgssapi3-heimdal  			
#sap libgssapi-krb5-2  			
#sap libgssdp-1.2-0  			
#sap libgstreamer1.0-0  			
#sap libgstreamer-gl1.0-0  		
#sap libgstreamer-plugins-base1.0-0  	
#sap libgtk2.0-0  				
#sap libgtk2.0-bin  			
#sap libgtk2.0-common  			
#sap libgtk-3-0  				
#sap libgtk-3-bin  			
#sap libgtk-3-common  			
#sap libgtk3-perl  			
#sap libgtkmm-3.0-1v5  			
#sap libgtksourceview-4-0  		
#sap libgtksourceview-4-common  		
#sap libgtop-2.0-11  			
#sap libgtop2-common  			
#sap libgudev-1.0-0  			
#sap libgupnp-1.2-0  			
#sap libgupnp-av-1.0-2  			
#sap libgupnp-dlna-2.0-3  			
#sap libgusb2  				
#sap libgweather-3-16  			
#sap libgweather-common  			
#sap libgxps2  				
#sap libhandy-0.0-0  			
#sap libharfbuzz0b  			
#sap libharfbuzz-icu0  			
#sap libhcrypto4-heimdal  			
#sap libheimbase1-heimdal  		
#sap libheimntlm0-heimdal  		
#sap libhtml-format-perl  			
#sap libhtml-form-perl  			
#sap libhtml-parser-perl  			
#sap libhtml-tagset-perl  			
#sap libhtml-tree-perl  			
#sap libhttp-cookies-perl  		
#sap libhttp-daemon-perl  			
#sap libhttp-date-perl  			
#sap libhttp-message-perl  		
#sap libhttp-negotiate-perl  		
#sap libhunspell-1.7-0  			
#sap libhx509-5-heimdal  			
#sap libhyphen0  				
#sap libibus-1.0-5  			
#sap libical3  				
#sap libice6  				
#sap libidn11  				
#sap libiec61883-0  			
#sap libieee1284-3  			
#sap libijs-0.35  				
#sap libimobiledevice6  			
#sap libinput10  				
#sap libinput-bin  			
#sap libio-html-perl  			
#sap libio-socket-ssl-perl  		
#sap libio-stringy-perl  			
#sap libip6tc2  				
#sap libipc-system-simple-perl  		
#sap libisl22  				
#sap libiw30  				
#sap libjack-jackd2-0  			
#sap libjansson4  					
#sap libjavascriptcoregtk-4.0-18  		
#sap libjbig0  				
#sap libjbig2dec0  			
#sap libjpeg8  				
#sap libjpeg-turbo8  			
#sap libjson-glib-1.0-0  			
#sap libjson-glib-1.0-common  		
#sap libk5crypto3  			
#sap libkeyutils1  			
#sap libklibc  				
#sap libkpathsea6  			
#sap libkrb5-26-heimdal  			
#sap libkrb5-3  				
#sap libkrb5support0  			
#sap libksba8  				
#sap liblcms2-2  				
#sap liblcms2-utils  			
#sap libldap-2.4-2  			
#sap libldap-common  			
#sap libldb2  				
#sap libllvm10  				
#sap libllvm9  				
#sap liblmdb0  				
#sap liblouis20  				
#sap liblouis-data  			
#sap liblouisutdml9  			
#sap liblouisutdml-bin  			
#sap liblouisutdml-data  			
#sap libltdl7  				
#sap liblwp-mediatypes-perl  		
#sap liblwp-protocol-https-perl  		
#sap liblzo2-2  				
#sap libmailtools-perl  			
#sap libmaxminddb0  			
#sap libmbim-glib4  			
#sap libmbim-proxy  			
#sap libmediaart-2.0-0  			
#sap libmm-glib0  				
#sap libmozjs-68-0  			
#sap libmp3lame0  				
#sap libmpfr6  				
#sap libmpg123-0  				
#sap libmtdev1  				
#sap libmtp9  				
#sap libmtp-common  			
#sap libmtp-runtime  			
#sap libmutter-6-0  			
#sap libmysqlclient21  			
#sap libnautilus-extension1a  		
#sap libndp0  				
#sap libnet-dbus-perl  			
#sap libnetfilter-conntrack3  		
#sap libnet-http-perl  			
#sap libnet-smtp-ssl-perl  		
#sap libnet-ssleay-perl  			
#sap libnfs13  				
#sap libnftnl11  				
#sap libnghttp2-14  			
#sap libnl-3-200  				
#sap libnl-genl-3-200  			
#sap libnl-route-3-200  			
#sap libnm0  				
#sap libnma0  				
#sap libnotify4  				
#sap libnotify-bin  			
#sap libnpth0  				
#sap libnspr4  				
#sap libnss3  				
#sap libnss-mdns  				
#sap libntfs-3g883  			
#sap libnuma1  				
#sap libnvpair1linux  			
#sap libogg0  				
#sap libopenjp2-7  			
#sap libopus0  				
#sap liborc-0.4-0  			
#sap libpackagekit-glib2-18  		
#sap libpam-fprintd  			
#sap libpam-gnome-keyring  		
#sap libpango-1.0-0  			
#sap libpangocairo-1.0-0  			
#sap libpangoft2-1.0-0  			
#sap libpangomm-1.4-1v5  			
#sap libpangoxft-1.0-0  			
#sap libpaper1  				
#sap libpaper-utils  			
#sap libparted2  				
#sap libparted-fs-resize0  		
#sap libpcap0.8  				
#sap libpcaudio0  				
#sap libpci3  				
#sap libpciaccess0  			
#sap libpcre2-32-0  			
#sap libpcsclite1  			
#sap libpeas-1.0-0  			
#sap libpeas-common  			
#sap libperl5.30  				
#sap libphonenumber7  			
#sap libpipeline1  			
#sap libpixman-1-0  			
#sap libpkcs11-helper1  			
#sap libplist3  				
#sap libplymouth5  			
#sap libpng16-16  				
#sap libpolkit-agent-1-0  			
#sap libpolkit-gobject-1-0  		
#sap libpoppler97  			
#sap libpoppler-cpp0v5  			
#sap libpoppler-glib8  			
#sap libprotobuf17  			
#sap libproxy1-plugin-gsettings  		
#sap libproxy1-plugin-networkmanager  	
#sap libproxy1v5  				
#sap libpsl5  				
#sap libpulse0  				
#sap libpulsedsp  				
#sap libpulse-mainloop-glib0  		
#sap libpwquality1  			
#sap libpwquality-common  			
#sap libpython3.8  			
#sap libqmi-glib5  			
#sap libqmi-proxy  			
#sap libqpdf26  					
#sap libraw1394-11  			
#sap librest-0.7-0  			
#sap libroken18-heimdal  			
#sap librsvg2-2  				
#sap librsvg2-common  			
#sap librtmp1  				
#sap librygel-core-2.6-2  			
#sap librygel-db-2.6-2  			
#sap librygel-renderer-2.6-2  		
#sap librygel-server-2.6-2  		
#sap libsamplerate0  			
sap libsane  				
sap libsane-common  			
sap libsane-hpaio  			
#sap libsasl2-modules  			
#sap libsbc1  				
#sap libsecret-1-0  			
#sap libsecret-common  			
#sap libsensors5  				
#sap libsensors-config  			
#sap libshout3  				
#sap libsigc++-2.0-0v5  			
#sap libsm6  				
#sap libsmbclient  			
#sap libsmbios-c2  			
#sap libsnapd-glib1  			
#sap libsndfile1  				
#sap libsnmp35  				
#sap libsnmp-base  			
#sap libsonic0  				
#sap libsoup2.4-1  			
#sap libsoup-gnome2.4-1  			
#sap libsoxr0  				
#sap libspectre1  				
#sap libspeechd2  				
#sap libspeex1  				
#sap libspeexdsp1  			
#sap libssh-4  				
#sap libstartup-notification0  		
#sap libstemmer0d  			
#sap libsynctex2  				
#sap libsysmetrics1  			
#sap libtag1v5  				
#sap libtag1v5-vanilla  			
#sap libtalloc2  				
#sap libtdb1  				
#sap libteamdctl0  			
#sap libtepl-4-0  				
#sap libtevent0  				
#sap libthai0  				
#sap libthai-data  			
#sap libtheora0  				
#sap libtie-ixhash-perl  			
#sap libtiff5  				
#sap libtimedate-perl  			
#sap libtotem-plparser18  			
#sap libtotem-plparser-common  		
#sap libtracker-control-2.0-0  		
#sap libtracker-miner-2.0-0  		
#sap libtracker-sparql-2.0-0  		
#sap libtry-tiny-perl  			
#sap libtss2-esys0  			
#sap libtwolame0  				
#sap libu2f-udev  				
#sap libuchardet0  			
#sap libudisks2-0  			
#sap libunity9  				
#sap libunity-protocol-private0  		
#sap libunity-scopes-json-def-desktop  	
#sap libunwind8  				
#sap libupower-glib3  			
#sap liburi-perl  				
#sap libusb-1.0-0  			
#sap libusbmuxd6  				
#sap libuutil1linux  			
#sap libuv1  				
#sap libv4l-0  				
#sap libv4lconvert0  			
#sap libvisual-0.4-0  			
#sap libvolume-key1  			
#sap libvorbis0a  				
#sap libvorbisenc2  			
#sap libvorbisfile3  			
#sap libvpx6  				
#sap libvte-2.91-0  			
#sap libvte-2.91-common  			
#sap libvulkan1  				
#sap libwacom2  				
#sap libwacom-bin  			
#sap libwacom-common  			
#sap libwavpack1  				
#sap libwayland-client0  			
#sap libwayland-cursor0  			
#sap libwayland-egl1  			
#sap libwayland-server0  			
#sap libwbclient0  			
#sap libwebkit2gtk-4.0-37  		
#sap libwebp6  				
#sap libwebpdemux2  			
#sap libwebrtc-audio-processing1  		
#sap libwhoopsie0  			
#sap libwhoopsie-preferences0  		
#sap libwind0-heimdal  			
#sap libwmf0.2-7  				
#sap libwmf0.2-7-gtk  			
#sap libwnck-3-0  				
#sap libwnck-3-common  			
#sap libwoff1  				
#sap libwrap0  				
#sap libwww-perl  				
#sap libwww-robotrules-perl  		
#sap libx11-6  				
#sap libx11-data  				
#sap libx11-protocol-perl  		
#sap libx11-xcb1  				
#sap libxatracker2  			
#sap libxau6  				
#sap libxaw7  				
#sap libxcb1  				
#sap libxcb-dri2-0  			
#sap libxcb-dri3-0  			
#sap libxcb-glx0  				
#sap libxcb-icccm4  			
#sap libxcb-present0  			
#sap libxcb-randr0  			
#sap libxcb-render0  			
#sap libxcb-res0  				
#sap libxcb-shape0  			
#sap libxcb-shm0  				
#sap libxcb-sync1  			
#sap libxcb-xfixes0  			
#sap libxcb-xkb1  				
#sap libxcb-xv0  				
#sap libxcomposite1  			
#sap libxcursor1  				
#sap libxdamage1  				
#sap libxdmcp6  				
#sap libxext6  				
#sap libxfixes3  				
#sap libxfont2  				
#sap libxft2  				
#sap libxi6  				
#sap libxinerama1  			
#sap libxkbcommon0  			
#sap libxkbcommon-x11-0  			
#sap libxkbfile1  				
#sap libxklavier16  			
#sap libxmlb1  				
#sap libxml-parser-perl  			
#sap libxml-twig-perl  			
#sap libxml-xpathengine-perl  		
#sap libxmu6  				
#sap libxmuu1  				
#sap libxpm4  				
#sap libxrandr2  				
#sap libxrender1  				
#sap libxres1  				
#sap libxshmfence1  			
#sap libxslt1.1  				
#sap libxss1  				
#sap libxt6  				
#sap libxtst6  				
#sap libxv1  				
#sap libxvmc1  				
#sap libxxf86dga1  			
#sap libxxf86vm1  				
#sap libyelp0  				
#sap libzfs2linux  			
#sap libzpool2linux  			
#sap linux-base  				
#sap linux-firmware  			
#sap linux-generic-hwe-20.04  		
#sap linux-headers-5.4.0-42  		
#sap linux-headers-5.4.0-42-generic  	
#sap linux-headers-5.4.0-48  		
#sap linux-headers-5.4.0-48-generic  	
#sap linux-headers-generic-hwe-20.04  	
#sap linux-image-5.4.0-42-generic  	
#sap linux-image-5.4.0-48-generic  	
#sap linux-image-generic-hwe-20.04  	
#sap linux-modules-5.4.0-42-generic  	
#sap linux-modules-5.4.0-48-generic  	
#sap linux-modules-extra-5.4.0-42-generic  
#sap linux-modules-extra-5.4.0-48-generic  
#sap linux-sound-base  			
#sap lshw  				
#sap ltrace  				
#sap lz4  					
#sap memtest86+  				
#sap mesa-vulkan-drivers  			
#sap mobile-broadband-provider-info  	
#sap modemmanager  			
#sap mokutil  				
#sap mousetweaks  				
#sap mscompress  				
#sap mtools  				
#sap mtr-tiny  				
#sap mutter 	 			
#sap mutter-common  			
#sap mysql-common  			
#sap nautilus  				
#sap nautilus-data  			
#sap nautilus-extension-gnome-terminal  	
#sap nautilus-sendto  			
#sap nautilus-share  			
#sap network-manager  			
#sap network-manager-gnome  		
#sap network-manager-openvpn  		
#sap network-manager-openvpn-gnome  	
#sap network-manager-pptp  		
#sap network-manager-pptp-gnome  		
#sap ntfs-3g  				
#sap openprinting-ppds 			
#sap openvpn  				
#sap orca  				
#sap p11-kit  				
#sap p11-kit-modules  			
#sap packagekit  				
#sap packagekit-tools  			
#sap parted  				
#sap patch  				
#sap pci.ids  				
#sap pcmciautils  				
#sap perl-openssl-defaults  		
#sap pinentry-curses  			
#sap pinentry-gnome3  			
#sap pkg-config  				
#sap plymouth  				
#sap plymouth-label  			
#sap plymouth-theme-spinner  		
#sap plymouth-theme-ubuntu-text  		
#sap policykit-1  				
#sap policykit-desktop-privileges  	
#sap poppler-data  			
#sap poppler-utils  			
#sap popularity-contest  			
#sap powermgmt-base  			
#sap ppp  					
#sap pptp-linux  				
sap printer-driver-brlaser  		
sap printer-driver-c2esp  		
sap printer-driver-foo2zjs  		
sap printer-driver-foo2zjs-common  	
sap printer-driver-m2300w  		
sap printer-driver-min12xxw  		
sap printer-driver-pnm2ppa  		
sap printer-driver-ptouch  		
sap printer-driver-pxljr  		
sap printer-driver-sag-gdi  		
sap printer-driver-splix  			
#sap psmisc  				
#sap publicsuffix  			
#sap pulseaudio  				
#sap pulseaudio-module-bluetooth  		
#sap pulseaudio-utils  			
#sap python3-apport  			
#sap python3-apt  				
#sap python3-blinker  			
#sap python3-brlapi  			
#sap python3-cairo  			
#sap python3-certifi  			
#sap python3-chardet  			
#sap python3-click  			
#sap python3-colorama  			
#sap python3-commandnotfound  		
#sap python3-cryptography  		
#sap python3-cups  			
#sap python3-cupshelpers  			
#sap python3-dateutil  			
#sap python3-debconf  			
#sap python3-debian  			
#sap python3-distro  			
#sap python3-distro-info  			
#sap python3-distupgrade  			
#sap python3-entrypoints  			
#sap python3-gdbm  			
#sap python3-gi-cairo  			
#sap python3-httplib2  			
#sap python3-ibus-1.0  			
#sap python3-idna  			
#sap python3-jwt  				
#sap python3-keyring  			
#sap python3-launchpadlib  		
#sap python3-lazr.restfulclient  		
#sap python3-lazr.uri  			
#sap python3-louis  			
#sap python3-macaroonbakery  		
#sap python3-oauthlib  			
#sap python3-problem-report  		
#sap python3-protobuf  			
#sap python3-pyatspi  			
#sap python3-requests  			
#sap python3-requests-unixsocket  		
#sap python3-rfc3339  			
#sap python3-secretstorage  		
#sap python3-simplejson  			
#sap python3-software-properties  		
#sap python3-speechd  			
#sap python3-systemd  			
#sap python3-talloc  			
#sap python3-tz  				
#sap python3-update-manager  		
#sap python3-urllib3  			
#sap python3-wadllib  			
#sap python3-xdg  				
#sap python3-xkit  			
#sap python-apt-common  			
#sap rfkill  				
#sap rsync  				
#sap rtkit  				
#sap rygel  				
#sap samba-libs  				
sap sane-utils  				
#sap sbsigntool  				
#sap seahorse  				
#sap secureboot-db  			
#sap sgml-base  				
#sap sgml-data  				
#sap shim  				
#sap shim-signed  				
#sap snapd  				
#sap software-properties-common  		
#sap software-properties-gtk  		
#sap sound-icons  				
#sap sound-theme-freedesktop  		
#sap speech-dispatcher  			
#sap speech-dispatcher-audio-plugins  	
#sap speech-dispatcher-espeak-ng  		
#sap spice-vdagent  			
#sap squashfs-tools  			
#sap ssl-cert  				
#sap strace  				
#sap switcheroo-control  			
#sap system-config-printer  		
#sap system-config-printer-common  	
#sap system-config-printer-udev  		
#sap tcpdump  				
#sap thermald  				
#sap tpm-udev  				
#sap tracker  				
#sap tracker-extract  			
#sap tracker-miner-fs  			
#sap ubuntu-desktop  			
#sap ubuntu-desktop-minimal 		
#sap ubuntu-docs  				
#sap ubuntu-drivers-common  		
#sap ubuntu-mono  				
#sap ubuntu-release-upgrader-core  	
#sap ubuntu-release-upgrader-gtk  		
#sap ubuntu-report  			
#sap ubuntu-session  			
#sap ubuntu-settings  			
#sap ubuntu-wallpapers  			
#sap ubuntu-wallpapers-focal  		
#sap udisks2  				
#sap ufw  					
#sap unattended-upgrades  			
#sap unzip  				
#sap update-inetd  			
#sap update-manager  			
#sap update-manager-core  			
#sap update-notifier  			
#sap update-notifier-common  		
#sap upower  				
#sap usb.ids  				
#sap usb-modeswitch  			
#sap usb-modeswitch-data  			
#sap usbmuxd  				
#sap usbutils  				
#sap uuid-runtime  			
#sap wbritish  				
#sap whoopsie  				
#sap whoopsie-preferences  		
#sap wireless-regdb  			
#sap wireless-tools  			
#sap wpasupplicant  			
sap x11-apps  				
sap x11-common  				
sap x11-session-utils  			
sap x11-utils  				
sap x11-xkb-utils  			
sap x11-xserver-utils  			
sap xauth  				
sap xbitmaps  				
sap xbrlapi  				
sap xcursor-themes  			
#sap xdg-dbus-proxy  			
#sap xdg-desktop-portal  			
#sap xdg-desktop-portal-gtk  		
#sap xdg-user-dirs-gtk  			
#sap xdg-utils  				
sap xfonts-base  				
sap xfonts-encodings  			
sap xfonts-scalable  			
sap xfonts-utils  				
sap xinit  				
sap xinput  				
#sap xml-core  				
sap xorg  					
sap xorg-docs-core  			
sap xserver-common  			
sap xserver-xephyr  			
sap xserver-xorg  				
sap xserver-xorg-core  			
sap xserver-xorg-input-all  		
sap xserver-xorg-input-libinput  		
sap xserver-xorg-input-wacom  		
sap xserver-xorg-legacy  			
sap xserver-xorg-video-all  		
sap xserver-xorg-video-amdgpu  		
sap xserver-xorg-video-ati  		
sap xserver-xorg-video-fbdev  		
sap xserver-xorg-video-intel  		
sap xserver-xorg-video-nouveau  		
sap xserver-xorg-video-qxl  		
sap xserver-xorg-video-radeon  		
sap xserver-xorg-video-vesa  		
sap xserver-xorg-video-vmware  		
sap xul-ext-ubufox  			
#sap xwayland  				
sap yaru-theme-gnome-shell  		
sap yaru-theme-gtk  			
sap yaru-theme-icon  			
sap yaru-theme-sound  			
sap yelp  					
sap yelp-xsl  				
#sap zenity  				
#sap zenity-common  			
#sap zfs-initramfs  			
#sap zfsutils-linux  			
#sap zfs-zed  				
#sap zip  					
#sap zsys	 				
