#sap amd64-microcode  	
#sap bash-completion  	
#sap bc  			
#sap bind9-dnsutils  	
#sap bind9-host  		
#sap bind9-libs  		
#sap cron  		
#sap dc  			
#sap ftp  			
#sap gettext-base  	
#sap hunspell-en-us  	
#sap intel-microcode  	
#sap libsasl2-2  		
#sap libsasl2-modules-db  	
#sap lsof  		
#sap manpages  		
#sap openssh-client  	
#sap pciutils  		
#sap perl  		
#sap perl-modules-5.30  	
#sap telnet  		
#sap time  		
#sap wamerican 		
