sap 	#amd64-microcode \ 	#standard
sap 	#bash-completion \ 	#standard
sap 	#bc \ 			#standard
sap 	#bind9-dnsutils \ 	#standard
sap 	#bind9-host \ 		#standard
sap 	#bind9-libs \ 		#standard
sap 	#cron \ 		#standard
sap 	#dc \ 			#standard
sap 	#ftp \ 			#standard
sap 	#gettext-base \ 	#standard
sap 	#hunspell-en-us \ 	#standard
sap 	#intel-microcode \ 	#standard
sap 	#libsasl2-2 \ 		#standard
sap 	#libsasl2-modules-db \ 	#standard
sap 	#lsof \ 		#standard
sap 	#manpages \ 		#standard
sap 	#openssh-client \ 	#standard
sap 	#pciutils \ 		#standard
sap 	#perl \ 		#standard
sap 	#perl-modules-5.30 \ 	#standard
sap 	#telnet \ 		#standard
sap 	#time \ 		#standard
sap 	#wamerican 		#standard
