#!

sudo apt purge 
	adduser \                 	#important
	apt \                     	#important
	apt-utils \               	#important
	bsdmainutils \            	#important
	bzip2 \                   	#important
	ca-certificates \         	#important
	console-setup \           	#important
	console-setup-linux \     	#important
	cpio \                    	#important
	dbus \                    	#important
	debconf-i18n \            	#important
	distro-info-data \        	#important
	dmidecode \               	#important
	dmsetup \                 	#important
	eject \                   	#important
	file \                    	#important
	gir1.2-glib-2.0 \         	#important
	gpgv \                    	#important
	groff-base \              	#important
	info \                    	#important
	init \                    	#important
	install-info \            	#important
	iproute2 \                	#important
	iputils-ping \            	#important
	isc-dhcp-client \         	#important
	isc-dhcp-common \         	#important
	kbd \                     	#important
	keyboard-configuration \  	#important
	kmod \                    	#important
	less \                    	#important
	libapparmor1 \            	#important
	libapt-pkg6.0 \          	#important
	libargon2-1 \             	#important
	libatm1 \                 	#important
	libbsd0 \                 	#important
	libcap2 \                 	#important
	libcap2-bin \             	#important
	libcryptsetup12 \         	#important
	libdbus-1-3 \             	#important
	libdevmapper1.02.1 \      	#important
	libdns-export1109 \       	#important
	libelf1 \                 	#important
	libestr0 \                	#important
	libexpat1 \               	#important
	libfastjson4 \            	#important
	libffi7 \                 	#important
	libfribidi0 \             	#important
	libgirepository-1.0-1 \   	#important
	libglib2.0-0 \            	#important
	libglib2.0-data \         	#important
	libgmp10 \                	#important
	libgnutls30 \             	#important
	libhogweed5 \             	#important
	libicu66 \                	#important
	libidn2-0 \               	#important
	libip4tc2 \               	#important
	libisc-export1105 \       	#important
	libjson-c4 \              	#important
	libkmod2 \                	#important
	liblocale-gettext-perl \  	#important
	libmagic1 \               	#important
	libmagic-mgc \            	#important
	libmnl0 \                 	#important
	libmpdec2 \               	#important
	libnetplan0 \             	#important
	libnettle7 \              	#important
	libnewt0.52 \             	#important
	libnss-systemd \          	#important
	libp11-kit0 \             	#important
	libpam-cap \             	#important
	libpam-systemd \          	#important
	libpopt0 \                	#important
	libpython3.8-minimal \    	#important
	libpython3.8-stdlib \     	#important
	libpython3-stdlib \       	#important
	libreadline8 \            	#important
	libseccomp2 \             	#important
	libslang2 \               	#important
	libsodium23 \             	#important
	libsqlite3-0 \            	#important
	libssl1.1 \               	#important
	libstdc++6 \              	#important
	libtasn1-6 \              	#important
	libtext-charwidth-perl \  	#important
	libtext-iconv-perl \      	#important
	libtext-wrapi18n-perl \   	#important
	libunistring2 \           	#important
	libxml2 \                 	#important
	libxtables12 \            	#important
	libyaml-0-2 \             	#important
	locales \                 	#important
	logrotate \               	#important
	lsb-release \             	#important
	man-db \                  	#important
	mime-support \            	#important
	nano \                    	#important
	netbase \                 	#important
	netcat-openbsd \          	#important
	netplan.io \              	#important
	networkd-dispatcher \     	#important
	openssl \                 	#important
	python3 \                 	#important
	python3.8 \               	#important
	python3.8-minimal \       	#important
	python3-cffi-backend \    	#important
	python3-dbus \            	#important
	python3-gi \              	#important
	python3-minimal \         	#important
	python3-nacl \            	#important
	python3-netifaces \       	#important
	python3-pkg-resources \   	#important
	python3-pymacaroons \     	#important
	python3-six \             	#important
	python3-yaml \            	#important
	readline-common \         	#important
	rsyslog \                 	#important
	shared-mime-info \        	#important
	sudo \                    	#important
	systemd \                 	#important
	systemd-sysv \            	#important
	systemd-timesyncd \       	#important
	tzdata \                  	#important
	ubuntu-advantage-tools \  	#important
	ubuntu-keyring \          	#important
	ubuntu-minimal \          	#important
	ucf \                     	#important
	udev \                    	#important
	vim-common \              	#important
	vim-tiny \                	#important
	whiptail \                	#important
	xdg-user-dirs \           	#important
	xkb-data \                	#important
	xxd \                     	#important
	xz-utils			#important
sudo apt autoremove

